### ISSUE TITLE
[UF 4.3] Argument 2 passed to str_contains() must be of the type string

### ISSUE THREAD

**Issue by pauljcurtis** [userfrosting/UserFrosting#1102]
Logging out throws the following error in UF 4.3 and earlier.

I ran Composer Update on UF 4.1. Afterwards I could no longer log in or log out without this error. I've installed 4.3.3 and the same error occurs.

> TypeError
Argument 2 passed to str_contains() must be of the type string, null given, called in \UserFrosting\app\vendor\userfrosting\cache\src\Driver\TaggableFileStore.php on line 112

**Comment by lcharette** [comment]
This is fixed by https://github.com/userfrosting/cache/releases/tag/4.4.1, which is used by UF 4.4

Previous version of UserFrosting used an older version of the Cache dependency. So if you update to the newer version, you'll be fine.

I'll see if a fix can be done for 4.3, might be able to fix something

**Comment by lcharette** [comment]
See v4.3.4 for the fix on the 4.3 branch. Upgrading to 4.4 is still preferred.
