### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#1130]
UF's support of PHP 8 is unknown at this time as we do not have it covered by the existing test matrix. We'll likely need to update some dependencies in order to support PHP 8, and may also have to raise the minimum version.

**Comment by lcharette** [comment]
I did try to add PHP 8 to the test matrix. The issue is not only most dependencies don't support PHP 8 code wise, they don't support PHP 8 **composer** wise. That is the big issue.

Biggest roadblock, we depend deeply on Laravel 5.8, which doesn't support PHP 8. So we need to upgrade to Laravel 7 first.

**Comment by Silic0nS0ldier** [comment]
PHP 8 can be supported without composer v2 correct? The only issue here would be that dependencies we currently use do not support PHP 8.

Just trying to keep the distinction clear there so that we don't end up waiting on something unnecessarily.

**Comment by lcharette** [comment]
Not related to composer v2. More of having a lot of  

```
"require": {
        "php": ">=7.1",
```

**Comment by lcharette** [comment]
PHP 8 support is now officially in the works for version 4.6 in the `develop` branch 💪.
