### ISSUE TITLE
Media File Management

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#278]
Just for a suggestion towards 0.3.0,
would you be able to add a media file management tool please? It may probably include this:
- User uploads their photos and videos in media page
- User can choose their media from the list of his/her media files
- Admin sets maximum total file size for each user
- Admin writes a javascript code like 
  var data = {multi_selection:true, ....}
  button.onclick(this, popupMediaSelection(data, callback));

You might know the one in Wordpress. It is really really useful for developers.

**Comment by alexweissman** [comment]
I'll think about it - my main goal for 0.3.0 is to get the core code organized and refactored.  But hopefully, the new structure will make it easier for others to extend UF with features like this!

**Comment by pitbulk** [comment]
@9tontruck if you are looking for a file management tool, check owncloud:
https://owncloud.org/

**Comment by 9tontruck** [comment]
Thank Pitbulk. After briefly looking through it, I feel it just seems like Dropbox. Is it one that we can use like Media in Wordpress dashboard?

**Comment by pitbulk** [comment]
https://wordpress.org/plugins/file-away/
https://wordpress.org/plugins/wp-front-end-repository/

**Comment by alexweissman** [comment]
Well I guess the question is, would a feature like this be considered part of the core UF codebase, or would it be a plugin?

UF isn't primarily a CMS, though I could see it being extended with CMS-like features/plugins for specific projects.  

However, I also know that several people have requested support for a gravatar/profile-pic feature in UF.  So, this leads to the general issue of user file uploading.  Would we need to do anything in particular to support file uploads?  If the developer stores uploaded files in the database, that seems like a fairly straightforward extension. But Wordpress seems to put uploaded files directly in the file system, so that might require some additional code for fetching, access control, etc.

On the frontend, an interactive media manager tool I think would be best implemented as a plugin.

**Comment by alexweissman** [comment]
Cross-reference with #192.
