### ISSUE TITLE
Server config for IIS

### ISSUE THREAD

**Issue by sucinimad** [userfrosting/UserFrosting#371]
Hi, I'm using the latest version of userFrosting (0.3), on Windows Server 2012, php 5.4 and mysql 5.6. I don't have access to php error log.

This is my directory tree view:
![userfrosting-directory](https://cloud.githubusercontent.com/assets/13373558/8738477/b275f892-2be4-11e5-90fe-c0b19caa23e3.png)

When I go to here to get started: http://testserver/userfrosting/public, I get a 404 error.

When I go here: http://sdmmpx.sandag.org.gerbera.arvixe.com/index.php, it automatically redirects to: http://sdmmpx.sandag.org.gerbera.arvixe.com/index.php/install/master

My tables are created. I get this form: 
![userfrosting-admin](https://cloud.githubusercontent.com/assets/13373558/8738503/2029d9b2-2be5-11e5-92d3-fa3c9a95be6a.png)

I tried to register but it goes no where. All it says is I have the incorrect token even when I copied the token straight from the db table. 

I think here is where it's having trouble locating the right directories. There's no styles on the form. Console gives me this:
![userfrosting404](https://cloud.githubusercontent.com/assets/13373558/8738535/9b29eaa8-2be5-11e5-85f3-d0ccc5bf0539.png)

I think it might be a permission problem but not sure how to proceed. Any help is appreciated. Thank you.

**Comment by alexweissman** [comment]
Looks like it is failing to rewrite the URLs for JS and CSS includes.  You'll need an appropriate configuration file for Windows Server (I believe that's IIS?)

Take a look at http://www.helicontech.com/ape/ for converting the `.htaccess` file to the configuration file you need, and feel free to join us in chat.

**Comment by alexweissman** [comment]
Not sure how popular IIS is.  Let's save it for 0.3.2.

**Comment by dorianmuthig** [comment]
I was running on IIS Express 10 with the following `web.config`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <!-- Add IIS configuration entries here. -->
    <system.webServer>
        <rewrite>
            <rules>
                <!-- Can't actually tell PHP that the mod_rewrite module is enabled, doesn't make sense -->
                <rule name="Forward all www. to non-www.  Remove this rule if you want both available." stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <conditions>
                        
                        <add input="{HTTP_HOST}" pattern="^www\.(.*)$" />
                    </conditions>
                    <action type="Redirect" redirectType="Permanent" url="http://{C:1}/{R:1}" />
                </rule>
                <rule name="Remove trailing slash from any non-directory path (canonicalization) - GET requests only" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_METHOD}" pattern="^GET$" ignoreCase="false" />
                        <add input="{URL}" pattern="(.+)/$" ignoreCase="false" />
                    </conditions>
                    <action type="Redirect" redirectType="Permanent" url="{C:1}" />
                </rule>
                <rule name="Dynamically rewrite base directory (see http://stackoverflow.com/questions/31062479/301-redirect-urls-that-are-also-being-rewritten)">
                    <match url="^.*$" ignoreCase="false" />
                    <conditions>
                        <add input="{R:0}#{URL}" pattern="^([^#]*)#(.*)\1$" ignoreCase="false" />
                    </conditions>
                    <action type="None" />
                </rule>
                <rule name="Forward any requested URLs that specifically contain index.php (see http://stackoverflow.com/questions/31062479/301-redirect-urls-that-are-also-being-rewritten)" stopProcessing="true">
                    <match url="^index\.php(?:/(.*))?$" />
                    <conditions>
                        <add input="{THE_REQUEST}" pattern="/index\.php" />
                    </conditions>
                    <action type="Redirect" redirectType="Permanent" url="{R:1}" />
                </rule>
                <rule name="Send the URI to index.php (Slim routing)" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

The web config file does not precisely mimic the mod_rewrite rules you used, but I'm not sure how to pass on the `E=BASE:%2` and `NE` `RewriteRule` parameters. I'll figure it out sometime, but URL routing seemed to work properly this way and I have yet to encounter any issues related to URL routing. Running with the DEVSENSE PHP development extension in Visual Studio works great like this, the only thing I'm missing is Twig template support, but the HTML syntax highlighter will serve me well enough for now. 
To make it work for you, simply create a file called `web.config`, paste the XML above into it, and save it to the `public` (or in your case the `wwwroot`) folder.
Since you mentioned you're running on PHP 5.4, which is _end-of-life_, you should upgrade to PHP 5.6. Upgrading your MySQL server to 5.7 probably also can't hurt.

**Comment by alexweissman** [comment]
This is amazing, thanks!

**Comment by Silic0nS0ldier** [comment]
Thought I'd provide an update on this.
I've put together a `web.config` (originally completely unaware of @dorianmuthig version already posted, making for a gruelling process).
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <configSections>
        
    </configSections>
    <system.webServer>
        <security>
            <requestFiltering>
                <verbs allowUnlisted="false">
                    <add verb="PUT" allowed="true" />
                    <add verb="POST" allowed="true" />
                    <add verb="GET" allowed="true" />
                    <add verb="DELETE" allowed="true" />
                </verbs>
            </requestFiltering>
        </security>
        <rewrite>
            <rules>
                <!-- Clear any inherited rules -->
                <clear />
                <!-- Dynamically rewrite base directory -->
                <rule name="Remove .../index.php/... from url">
                    <match url="^index\.php/(.*)$" />
                    <action type="Redirect" redirectType="Permanent" url="{R:1}" />
                </rule>
                <!-- Remove trailing slash from any non-directory path (canonicalization) - GET requests only-->
                <rule name="Remove trailing slash">
                    <match url="(.*)/$" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Redirect" redirectType="Permanent" url="{R:1}" />
                </rule>
                <!-- Send the URI to index.php (Slim routing) -->
                <rule name="Rewrite to index.php" stopProcessing="true">
                    <match url=".*" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILEDIR}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" />
                </rule>
            </rules>
        </rewrite>
        <!-- Set index.php as default document, and clear inherited defaults. -->
        <defaultDocument enabled="true">
            <files>
                <clear />
                <add value="index.php" />
            </files>
        </defaultDocument>
        <httpProtocol>
            <customHeaders>
                <clear />
                <add name="Accept-Encoding" value="gzip,deflate" />
            </customHeaders>
        </httpProtocol>
        <!-- Whitelist specific static file types -->
        <staticContent>
            <!-- Clear inherited rules -->
            <clear />
            <!-- Set content expiration time (31 days for every static file listed) -->
            <!--<clientCache cacheControlMode="UseMaxAge" cacheControlMaxAge="31.00:00:00" />-->
            <!-- Atom feeds -->
            <mimeMap fileExtension=".atom" mimeType="application/atom+xml" />
            <mimeMap fileExtension=".xml" mimeType="application/atom+xml, application/rss+xml, application/xhtml+xml, application/xml, text/xml" />
            <!-- JS -->
            <mimeMap fileExtension=".js" mimeType="application/js" />
            <!-- JSON -->
            <mimeMap fileExtension=".json" mimeType="application/json" />
            <!-- EOT font -->
            <mimeMap fileExtension=".eot" mimeType="application/vnd.ms-fontobject" />
            <!-- TTF fonts -->
            <mimeMap fileExtension=".ttf" mimeType="application/x-font-ttf" />
            <!-- Web App Manifest -->
            <mimeMap fileExtension=".webapp" mimeType="application/x-web-app-manifest+json" />
            <!-- XHTML -->
            <mimeMap fileExtension=".xhtml" mimeType="application/xhtml+xml" />
            <mimeMap fileExtension=".xht" mimeType="application/xhtml+xml" />
            <mimeMap fileExtension=".html" mimeType="application/xhtml+xml" />
            <mimeMap fileExtension=".htm" mimeType="application/xhtml+xml" />
            <!-- Images -->
            <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
            <mimeMap fileExtension=".png" mimeType="image/png" />
            <mimeMap fileExtension=".ico" mimeType="image/x-icon" />
            <!-- WOFF/2 fonts -->
            <mimeMap fileExtension=".woff" mimeType="application/x-font-woff" />
            <mimeMap fileExtension=".woff2" mimeType="font/woff2" />
            <!-- CSS -->
            <mimeMap fileExtension=".css" mimeType="text/css" />
            <!-- Plain text -->
            <mimeMap fileExtension=".txt" mimeType="text/plain" />
            <!-- HTML Component -->
            <mimeMap fileExtension=".htc" mimeType="text/x-component" />
        </staticContent>
    </system.webServer>
</configuration>
```
Its a work in progress, but results thus far are promising.

However, there is a catch.
Unlike Apache, IIS by default blocks `PUT` and `DELETE` HTTP verbs for the PHP handler. Thus far there doesn't appear to by anyway this can be cleanly done in `web.config` (at least no way to is a universal solution).

As such, in order to get UF v4 working correctly in IIS, developers will have to add `PUT` and `DELETE` to the PHP handler manually.

If anyone has any bright ideas regarding how the HTTP verbs can be dynamically added, I'm all ears.

**Comment by dorianmuthig** [comment]
To pass other types of HTTP requests besides the default `GET`, `HEAD`, and `POST` request types to the CGI process in IIS you need to specify them in the CGI handler configuration.
This is typically done globally for the entire web server, but can be done on a per directory basis, if the request filtering module is installed, and overriding has been allowed. This is not common, and configuring a server in this manner for production environments is highly discouraged. You typically own your server, or have full administrative access to the virtual instance on which it runs and can change the  configuration as follows in `applicationhost.config` (for IIS Express):
```xml
<configuration>
    <!-- standard stuff here -->
    <system.applicationHost>
        <sites>
            <!-- default site here -->
            <site name="OtherSiteLocation" id="2">
                <application path="/" applicationPool="UnmanagedClassicAppPool">
                    <virtualDirectory path="/" physicalPath="C:\InetPub\path\to\some\webroot" />
                </application>
                <bindings>
                    <binding protocol="http" bindingInformation="*:12345:localhost" />
                </bindings>
            </site>
            <!-- more sites here -->
        </sites>
    </system.applicationHost>
    <system.webServer>
        <!-- other stuff here -->
        <fastCgi>
            <application fullPath="C:\Program Files (x86)\IIS Express\PHP\v7.1\php-cgi.exe" monitorChangesTo="C:\Program Files (x86)\IIS Express\PHP\v7.1\php.ini" activityTimeout="600" requestTimeout="600" instanceMaxRequests="10000">
                <environmentVariables>
                    <environmentVariable name="PHPRC" value="C:\Program Files (x86)\IIS Express\PHP\v7.1\" />
                    <environmentVariable name="PHP_FCGI_MAX_REQUESTS" value="10000" />
                </environmentVariables>
            </application>
            <!-- more fast-CGI handlers here (other PHP versions, etc...) -->
        </fastCgi>
        <!-- other stuff here -->
    </system.webServer>
    <location path="" overrideMode="Allow"><!-- do not allow override in production -->
        <system.webServer>
            <modules>
                <!-- standard stuff here -->
            </modules>
            <handlers accessPolicy="Read, Script">
                <add name="PHP71_via_FastCGI" path="*.php" verb="GET,HEAD,POST" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v7.1\php-cgi.exe" resourceType="Either" requireAccess="Script" />
                <add name="Phar-PHP71_via_FastCGI" path="*.phar" verb="GET,HEAD,POST" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v7.1\php-cgi.exe" resourceType="Either"  requireAccess="Script" />
                 <!-- more stuff here -->
             </handlers>
        </system.webServer>
    </location>
    <location path="OtherSiteLocation">
        <system.webServer>
            <handlers>
                <add name="php-7.1" path="*.php" verb="GET,HEAD,POST" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v7.1\php-cgi.exe" resourceType="Either" requireAccess="Script" />
            </handlers>
            <defaultDocument>
                <files>
                    <clear />
                    <add value="index.php" />
                </files>
            </defaultDocument>
        </system.webServer>
    </location>
    <!-- more locations -->
</configuration>
```
So long as you know the path to the script processor, and `overrideMode` for the location your site runs under is set to `Allow`, you should be able to get away with a simple re-declaration of the handler with the request methods you want in the `verb` attribute in the `system.webServer` section. No guarantees, this is not what you are supposed to do. You may need to clear the existing list before adding new ones (see `defaultDocument` section).

Generally, however, you should avoid using HTTP request methods besides `HEAD`, `GET`, and `POST`. Their use is uncommon and support may be poor.

**Comment by Silic0nS0ldier** [comment]
Your point about configuration files modifying controllers makes sense.

Since UserFrosting uses PUT and DELETE HTTP verbs in some API-like controller methods, giving the PHP handler access is a requirement at this point.

Once the `web.config` is finalised, well have to make sure IIS setup is properly documented (for IIS Express and full IIS with manager).

**Comment by dorianmuthig** [comment]
In the example in my previous message, you can see

```xml
<location path="OtherSiteLocation">
    <system.webServer>
        <handlers>
            <add name="php-7.1" path="*.php" verb="GET,HEAD,POST" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v7.1\php-cgi.exe" resourceType="Either" requireAccess="Script" />
        </handlers>
        <defaultDocument>
            <files>
                <clear />
                <add value="index.php" />
            </files>
        </defaultDocument>
    </system.webServer>
</location>
```

where `OtherSiteLocation` is the name of the site in IIS. This is what the site configuration looks like. The global one is the one above it.
To override the allowed request methods that are passed to the request handler, you would construct a `web.config` for placing in the document root like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <!-- Add IIS configuration entries here. -->
    <system.webServer>
        <security>
            <requestFiltering>
                <verbs allowUnlisted="false">
                    <add verb="GET" allowed="true" />
                    <add verb="PUT" allowed="true" />
                    <add verb="DELETE" allowed="true" />
                    <add verb="POST" allowed="true" />
                    <add verb="HEAD" allowed="true" />
                    <add verb="PATCH" allowed="true" />
                    <add verb="OPTIONS" allowed="true" />
                </verbs>
            </requestFiltering>
        </security>
        <handlers>
            <clear />
            <add name="php-7.1" path="*.php" verb="GET,PUT,DELETE,POST,HEAD,PATCH,OPTIONS" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v7.1\php-cgi.exe" resourceType="Either" requireAccess="Script" />
            <add name="php-7.1-phar" path="*.phar" verb="GET,PUT,DELETE,POST,HEAD,PATCH,OPTIONS" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v7.1\php-cgi.exe" resourceType="Either" requireAccess="Script" />
        </handlers>
        <rewrite>
            <rules>
                <!-- Can't actually tell PHP that the mod_rewrite module is enabled, doesn't make sense -->
                <rule name="Forward all www. to non-www.  Remove this rule if you want both available." stopProcessing="true">
                    <match url="^(.*)$" ignoreCase="false" />
                    <conditions>

                        <add input="{HTTP_HOST}" pattern="^www\.(.*)$" />
                    </conditions>
                    <action type="Redirect" redirectType="Permanent" url="http://{C:1}/{R:1}" />
                </rule>
                <rule name="Remove trailing slash from any non-directory path (canonicalization) - GET requests only" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
                        <add input="{REQUEST_METHOD}" pattern="^GET$" ignoreCase="false" />
                        <add input="{URL}" pattern="(.+)/$" ignoreCase="false" />
                    </conditions>
                    <action type="Redirect" redirectType="Permanent" url="{C:1}" />
                </rule>
                <rule name="Dynamically rewrite base directory (see http://stackoverflow.com/questions/31062479/301-redirect-urls-that-are-also-being-rewritten)">
                    <match url="^.*$" ignoreCase="false" />
                    <conditions>
                        <add input="{R:0}#{URL}" pattern="^([^#]*)#(.*)\1$" ignoreCase="false" />
                    </conditions>
                    <action type="None" />
                </rule>
                <rule name="Forward any requested URLs that specifically contain index.php (see http://stackoverflow.com/questions/31062479/301-redirect-urls-that-are-also-being-rewritten)" stopProcessing="true">
                    <match url="^index\.php(?:/(.*))?$" />
                    <conditions>
                        <add input="{THE_REQUEST}" pattern="/index\.php" />
                    </conditions>
                    <action type="Redirect" redirectType="Permanent" url="{R:1}" />
                </rule>
                <rule name="Send the URI to index.php (Slim routing)" stopProcessing="true">
                    <match url="^" ignoreCase="false" />
                    <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.php" appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

This should allow you to run any RESTful service in accordance with the [Microsoft/api-guidelines](https://github.com/Microsoft/api-guidelines) using PHP and [slimphp/Slim](https://github.com/slimphp/Slim). You will need to adjust for the path to your PHP interpreter, though the location provided is the default that would be used in IIS Express for PHP 7.1, when configured through Web-PI (which I can't recommend anyone use, but DEVSENSE PHP keeps nagging about it, so I just put a symlink there).

Please note, overriding the options for response compression, mime type or cache control headers on a per directory basis is not recommended, use the server's global configuration for that, unless you explicitly need to provide incorrect responses (though why would you?). Overriding request headers or anything to do with the transport protocol is generally bad. 

Since the URLs are rewritten anyway, you don't need a default document for the directory, or can ignore whatever it may be set to.

I have not tried the configuration, proceed with caution.

**Comment by alexweissman** [comment]
> Generally, however, you should avoid using HTTP request methods besides HEAD, GET, and POST. Their use is uncommon and support may be poor.

This...is absurd.  `PUT` and `DELETE` are part of HTTP specs and necessary to implement a  RESTful API properly.

**Comment by Silic0nS0ldier** [comment]
Well, technically what's in UserFrosting isn't a RESTful API, as its dependant on the user being logged in.

A true RESTful service has no concept of a login session. And security is maintained by not leaking credentials necessary (such as an API key in the case of many services) to access protected routes.

Still, there is no issue with using HTTP verbs other than GET and POST. Just cause they are mostly used, does not make using others wrong.

**Comment by alexweissman** [comment]
True, but we do try to follow a ["mostly RESTful" approach](https://learn.userfrosting.com/routes-and-controllers/rest/restful-endpoints), which means using the correct verbs for methods, and modeling URLs as identifiers for things (resources), not actions.

Anyway, glad that this is getting sorted out!

**Comment by dorianmuthig** [comment]
> **alexweissman** wrote:
> 
> This...is absurd. `PUT` and `DELETE` are part of HTTP specs and necessary to implement a RESTful API properly.

It is absolutely not absurd. The headache you are having *right here* is case in point. Users in hosting environments, which do not have the ability to change these settings will not be able to use your application. This is merely a compatibility issue. In that regard, the HTTP specification becomes irrelevant.

> **Silic0nS0ldier** wrote:
> 
> Still, there is no issue with using HTTP verbs other than GET and POST. Just cause they are mostly used, does not make using others wrong.

Well that seems rather obvious, no? However, just because the protocol standard makes it available does not mean all implementation transports will feature all of it. In fact, most don't.

Again, my recommendation is still, that you confine yourself to `GET` and `POST` as it is highly unlikely to cause problems, if you do it that way. You can of course do as I described above to enable other method verbs, including ones which *aren't* in the HTTP standard specification (yes, that works, too).

**Comment by lcharette** [comment]
> Users in hosting environments, which do not have the ability to change these settings will not be able to use your application

I see this the same way as if someone would say "You require PHP >= 5.6, but my environment only support 5.5.x!!". If the app is not compatible with your system because your system is out of date, it's not the app fault. 

Is there a list of system/server that support `PUT` and `DELETE` ?

**Comment by alexweissman** [comment]
We confined ourselves to `GET` and `POST` in v3 because I was worried about compatibility issues.  Since then, I realized that this was wrong.  Using a `POST` request to delete a resource, for example, is just plain wrong.  

`PUT` and `DELETE` are the proper verbs to use, and if we don't use them, people will complain.  And we'll have to say "it's because we need to support the rare occasion where someone uses IIS but for some reason doesn't have the ability to configure their server."  As far as I'm concerned, anyone using IIS should be in an environment where they can change the necessary settings to support these _standard_ HTTP verbs.

**Comment by Silic0nS0ldier** [comment]
I've pushed up a feature branch ([feature-iis-support](https://github.com/userfrosting/UserFrosting/compare/feature-iis-support)). Once all UserFrosting functions have been tested under IIS (and some documentation is ready), it should be ready to be merged with the develop branch.

**Comment by dorianmuthig** [comment]
> **alexweissman** wrote:
>
> We confined ourselves to `GET` and `POST` in v3 because I was worried about compatibility issues. Since then, I realized that this was wrong. Using a `POST` request to delete a resource, for example, is just plain wrong.

There is absolutely nothing wrong with that. **Nothing**. You are entitled to your opinion, and you can do as you like. This is your project and as such, this is entirely your prerogative. I won't fault you for doing it this way anymore than I already have. Carry on, eat your eggs over easy, stir-fried or sunny side up. I don't care. 🙂

> **Silic0nS0ldier** wrote:
> 
> I've pushed up a feature branch ([feature-iis-support](https://github.com/userfrosting/UserFrosting/compare/feature-iis-support)). Once all UserFrosting functions have been tested under IIS (and some documentation is ready), it should be ready to be merged with the develop branch.

Took a look at it. You're doing it wrong. Rewriting `/index.php/` paths in the URL is unnecessary. Simply pass all requests which are not files on disk to the `index.php` script in the document root, like I have done in my example. Redirecting a trailing `index.php` in the URL is optional, but makes for prettier URLs, just in case someone somehow decides to enter it into their browsers address bar, without breaking anything.
It is also unwise to set the `resourceType` for the FastCGI handler to anything other than `Script`. As this is CGI/FastCGI, this may result in the resource being served as a `File` type resource.

**Comment by Silic0nS0ldier** [comment]
The rewriting of `index.php` is to match the behaviour of the other web server configuration files. (otherwise there will be people complaining about why `x` doesn't work the same as `y`.)

Example handler mapping was based on yours, which does the same thing (well, I missed `requireAccess="Script"`). It may well serve the php file instead of process it, but I yet to test it out. Either way, easy change.

**Comment by alexweissman** [comment]
I did the rewrite for `/index.php/` URLs mainly as a way to canonicalize and help devs avoid [SEO penalties for duplicate content](https://support.google.com/webmasters/answer/139066).

**Comment by dorianmuthig** [comment]
The `/index.php/` method is a hack to enable processing of URL paths in PHP, if you don't have some form of URL rewriting in place. This was common in the Apache httpd 1.3 days (using the `AcceptPathInfo` directive) to let you have your cake and eat it too when it comes to *pretty URLs*. In IIS, unless the `add` element for the handler serving the request has the `allowPathInfo` XML attribute set to `true`. This is not the default, setting it to true will break PHP, and because both behaviors are *wrong* for PHP/CGI, you need to have the `cgi.fix_pathinfo` setting in `php.ini` set to `1` or `true` to make PHP work with IIS.
You shouldn't get any SEO penalty for duplicate content, if you don't link to it. In IIS those links won't work (file doesn't exist) and be passed to Slim, which won't have a route and perform the not found default action (whatever you've set it to). By all means, leave it in, if it makes you feel god about yourself, though. It doesn't really matter, unless you want to be able to use an URL like that for some weird reason. In that context it is generally not good to redirect URLs before making sure the underlying application doesn't have a route for it.

**Comment by Silic0nS0ldier** [comment]
SEO is always evolving. Social Media now impacts rankings, so something like 'only linking to a single url on the site', simply won't cut it. If people start sharing different variations of your url, your SEO takes a hit.

As for not redirecting if the application underneath doesn't have a route (or file) for it, there isn't any other efficient way to handle this. (PHP could do it, but I hardly consider that efficient)

**Comment by Silic0nS0ldier** [comment]
If you have any proposal for a better system, create a new issue for it, as this is getting off topic.

**Comment by alexweissman** [comment]
So, do we have an agreed-upon boilerplate IIS config file that we can merge into the main repo?

**Comment by Silic0nS0ldier** [comment]
Been running our site of IIS for awhile now, without issue. I'm confident that it's reliable.

However I'd like to actually make sure the copy on my server is the same as the copy in the branch (think I've done some clean up). Plus throw a recipe together for the docs. Would've had this already sorted, but I'm currently swamped with uni assignments. Should be free to finish this off by week after next.

**Comment by abdullahseba** [comment]
Works fine for me too, but the `<handlers>` section doesn't not seem to work.

**Comment by Silic0nS0ldier** [comment]
Handlers is fully dependent on the environment, so that part will have to be covered by the recipe.

**Comment by Silic0nS0ldier** [comment]
Finally got some free time, should finally be put to rest this week.

**Comment by Silic0nS0ldier** [comment]
A recipe has been added to the docs regarding the potential extra steps required. `feature-iis-support` branch is done, and ready to be merged with `develop`.

**Comment by Silic0nS0ldier** [comment]
Just putting this here to investigate later.
[Apache emulator](https://www.iis.net/downloads/community/2009/10/ape-apache-emulator)

**Comment by abdullahseba** [comment]
Updated 2009 😟

**Comment by alexweissman** [comment]
Ok, it's been added!  See https://github.com/userfrosting/UserFrosting/commit/c71c8f96c90c545223a37e350fa9c62f32d7733f
