### ISSUE TITLE
"Virtual file" routes (config.js, theme.css) and security in nginx

### ISSUE THREAD

**Issue by r3wt** [userfrosting/UserFrosting#427]
![img](http://puu.sh/kOzXG/e93ac76bf0.png)

**Comment by r3wt** [comment]
actually, i'm now seeing this issue on all forms. @alexweissman can you offer some insight here on which files i need to look?

**Comment by r3wt** [comment]
pinpointed the problem 

![img](http://puu.sh/kOzXG/e93ac76bf0.png)

**Comment by r3wt** [comment]
It's possible that this issue is related to HHVM, i'm not sure.

**Comment by alexweissman** [comment]
So, these are both dynamically loaded by UF via routes in `BaseController.php`.  Maybe something is going wrong there?

**Comment by cmy82** [comment]
Figured out the issue. Look at issue https://github.com/alexweissman/UserFrosting/issues/461

**Comment by alexweissman** [comment]
I believe this is still a separate issue.  Basically, @r3wt has nginx configured in a certain way that prevents a certain type of security vulnerability (see http://cnedelcu.blogspot.com/2010/05/nginx-php-via-fastcgi-important.html), but also prevents it from resolving the routes for these "virtual files".

So, for nginx users, we need to find a way to permit these routes to be accessed while still closing the vulnerability.

**Comment by cmy82** [comment]
Not very familiar with Nginx and just really getting into the technical side of routing/slim, etc, but would it be possible to actually write the file when the session is created and just check some variable or condition to say when the file becomes invalid; something other than a timestamp. That way you won't incur the overhead a read/write on every request and since the file exists, you can get past the Nginx/FastCGI bug. This is assuming that just because the file exists, the routing won't actually serve the file and that you can still reference the site variable virtually.

**Comment by alexweissman** [comment]
Is this still an issue with our dynamically-served assets in v4?

**Comment by alexweissman** [comment]
This is no longer an issue, with the default nginx config file we provide.
