### ISSUE TITLE
i18n for entire templates

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#436]
We have a good system for translating smaller chunks of text into other languages (via `MessageTranslator`).  However, this seems like it would break down when I want to translate entire template files at a time - I don't want to have to stick all of my content into one gigantic translation file!

Fortunately, Twig comes to the rescue.  Using Twig [extends](http://twig.sensiolabs.org/doc/tags/extends.html), we can write a base template in English, and then block out the translatable content in a child template:

**message.twig**

```
<p>
    {% block greeting %}
        Hello, {{name}},
    {% endblock %}
</p>
<p>
    {% if user.online %}
        {% block body_online %}
            You have been online for {{minutes}} minutes.
        {% endblock %}
    {% else %}
        {% block body_offline %}
            You are currently offline.
        {% endblock %}
    {% endif %}
</p>
```

**message.es_ES.twig**

```
{% block greeting %}
    Hola, {{name}},
{% endblock %}

{% block body_online %}
    Usted ha estado en línea por {{minutes}} minutos.
{% endblock %}

{% block body_offline %}
    Usted se encuentra fuera de línea.
{% endblock %}
```

So, all we really need then is a method that uses the authenticated user's locale to automatically select the appropriate child language template.

This idea was generated in [chat](https://gitter.im/alexweissman/UserFrosting/archives/2015/10/20).

**Comment by markfischoff** [comment]
I am really fond of this idea. I would rather have the translation separated from the theme.
I propose something similar to Prestashop aproach, since i think this would keep the translation separated from the theme/plugins and improve the number of files translated by UF Community.

For those who don't know how Prestashop translation works, here are some screenshots.

Locale/Language page: gives you the option to download translation from prestashop 
![Image of locale page](http://i.imgur.com/z5ZCMbT.png)

You can translate yourself any of the front/backend/emails
![Image of translation page](http://i.imgur.com/y9f6pyW.png)

The translation page (not the perfect way) with collapsible areas and untranslated fields counts
![Image of locale page](http://i.imgur.com/fwqF573.png)

And lastly the code used in their smarty template engine
![Image of locale page](http://i.imgur.com/erd4xB2.png)

I believe trying to use a similar approach, 
*You don't need 10 child themes for a multi language app.
*It's more easy to translate, than to follow all the theme's code.
*Plugins can have their own translations
*Maybe a repo of translations (so you don't need to download all)

I don't think prestashop is perfect, or anything, but as a Romanian, to find a language pack (even if not perfect) that is easy to update is a life/time saver.

**Comment by alexweissman** [comment]
Hmm, ok so it looks like it uses something similar to [`gettext`](https://en.wikipedia.org/wiki/Gettext).
My issue with `gettext` is that since the translations are directly mapped to the English text, if you change the content, you have to go back and update all of the translations - even if the change was very minor and the translated content doesn't really need to change.

Just to clarify, with my approach we wouldn't need child themes.  We would have child *templates*, but these would still be part of the main `default` theme.

I also feel that the last two points could easily be addressed with my concept, as long as the translated templates are put into a file structure that matches the default theme.

I agree though, that a frontend interface for creating and managing translations would be useful.
