### ISSUE TITLE
Point System

### ISSUE THREAD

**Issue by Endroe** [userfrosting/UserFrosting#439]

**Comment by Netrilix** [comment]
Since so many sites handle points systems differently (eg. will it be done by post count, votes for posts, votes directly for the user, activity-based, etc.) that I might be best to just have simple functions for adding and subtracting points, and let developers decide how to handle it individually on their own sites.

**Comment by alexweissman** [comment]
This sounds like a great candidate for a plugin!

**Comment by Netrilix** [comment]
See #458 for a possible solution to this
