### ISSUE TITLE
Group admin

### ISSUE THREAD

**Issue by cvpsmith** [userfrosting/UserFrosting#454]
There was an earlier post about "delegating to group admin" whereby you could set up special "group admin" users who have special permissions such as creating users within a specific group.  It was mentioned that this had been implemented in the butterflyknife branch and I assume that it is somehow done via Group authorization rules, but I haven't found any documentation as to how to do this.  Can someone point me in the right direction?

Thanks in advance...

**Comment by alexweissman** [comment]
This post might help you: http://stackoverflow.com/questions/33366326/what-is-the-best-way-to-add-a-parent-group-to-user-groups-in-userfrosting

**Comment by cvpsmith** [comment]
Thanks for the info Alex.  It's not EXACTLY what I'm wanting to do, but it's sort of close.  Basically, I want to be able to assign group managers to each group and give those managers the ability to create users within the group they manage.  

I was under the impression that this was possible in the butterflyknife branch of UserFrosting (without changing the underlying code); is that not the case?

Thanks in advance...

**Comment by alexweissman** [comment]
Can you link to the issue?  `butterflyknife` was the codename for the `0.2.x` branch, which is obsolete at this point.  I don't think we explicitly implemented group managers.  The point was just that `butterflyknife` *can* support that functionality via authorization hooks (which 0.3.x also supports).

**Comment by cvpsmith** [comment]
The original post was [here.](https://github.com/alexweissman/UserFrosting/issues/23)

I think that's where I was confused.  I was thinking that I might be able to do this via the Group Authorization Rules page, but it appears that some coding would also be required.  

Thanks for the clarification!

**Comment by alexweissman** [comment]
No problem.  I think the term "group" is misleading, because you naturally want to put each set of users into a different group (for example, regional offices).  In UserFrosting, the term "group" really means "role".  

So, even if you have managers for each regional office, they still all have the same role of "regional manager".  Likewise, all employees, no matter their location, might still have the same roles as one another.

So for your scenario, I would model it with just two groups - "Manager" and "User".  You would then need to implement some other relational structure to horizontally partition managers and users.

**Comment by alexweissman** [comment]
Let us know if you're still having problems with this.  I do have a [plan](http://stackoverflow.com/questions/32937242/does-this-make-sense-as-a-way-to-implement-role-based-access-control) for separating roles and groups.
