### ISSUE TITLE
Checkbox processing in userfrosting.js

### ISSUE THREAD

**Issue by ssnukala** [userfrosting/UserFrosting#477]
When processing a form with special type of checkboxes generated by http://davidstutz.github.io/bootstrap-multiselect/ the userfrosting.js ufFormSubmit function is force reading all the checkboxes and appending to the POST queue 
The special checkboxes created by bootstrap-multiselect do not have a "name" and are just used for UI purposes to capture multi select. So the resulting POST array has a lot of 1s and 0s values without a name property. 

So we will need a mechanism to ignore the checkboxes if they don't have a "name" associated with them. 

These will only be special cases like this, otherwise any checkbox with a name will go thru properly in the POST array

**Comment by alexweissman** [comment]
After some thought, I'd say that maybe UF should *not* "binarize" checkboxes by default, because it could generate unexpected behavior for developers who are used to the way that checkboxes normally work.

I propose that we stop "binarizing" checkboxes by default.  Instead, we should have some special marker (either a `class` or `data-*` attribute), that signals to UF when it should binarize the checkbox.

**Comment by ssnukala** [comment]
ok, that works then only those checkboxes tagged with the attribute will be picked up and everything else will be passed as they are.

**Comment by alexweissman** [comment]
yeah, I think that's a good approach.  I personally hate the default behavior of checkboxes, but maybe some people like it.

**Comment by alexweissman** [comment]
Ok, I've started working on this with the `uf-form` jQuery plugin, coming up in v4.0.

**Comment by alexweissman** [comment]
This is implemented with the `binaryCheckboxes` option in [`uf-form.js`](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/core/assets/js/uf-form.js#L56) in v4.
