### ISSUE TITLE
phpmailer throws SMTP Error: data not accepted

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#487]
Hi,

When the server tries to send an email, it throws "SMTP Error: data not accepted"
I have been trying to fix this problem for a couple days.

I did lots searches on google and could find that this error is made when $From and smtp's $userName are different. So I tried to find the place where I can change in userfrosting folder but I couldn't find it. 

Would you please tell me where I should fix?

Thanks

**Comment by alexweissman** [comment]
Yes, one of the common reasons that an SMTP server will reject a message is when the SMTP username and the message `From` header do not match. 

Do you just want to change them so that they are the same?  By default, UF uses the `admin_email` in Site Settings for the From header for the various emails it sends.  So, you could just change that address in Site Settings to match your SMTP username.

If you actually do want to send email with a From header that is different from the SMTP username, you will need to be able to modify the postfix config file in your mail server.  If you have your own mail server this is possible (see my recent question on SE: http://serverfault.com/questions/746165/in-postfix-how-can-i-allow-only-certain-users-to-send-mail-as-any-other-user/746480#746480).

**Comment by 9tontruck** [comment]
Clearly, I want to send emails from smtp username. 
In the smtp setting in "config-userfrosting.php", it asks smtp username with password right? If I put abc@domain.com with a correct password, I think the server should be able to send emails from that smtp username. 
Would you tell me where I can change From head so I have the same email address as smtp username?

**Comment by alexweissman** [comment]
you can do this in the admin interface actually.  Configuration -> Site Settings -> Account Management Email.

**Comment by 9tontruck** [comment]
Oh great, it worked. Thanks a lot!

**Comment by alexweissman** [comment]
no problem!
