### ISSUE TITLE
Hook to modify UF's Twig global variables at runtime

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#488]
We recently ran into a case where UF and Grav would not work together because they share the names of Twig globals (most notably, `site`).

We talked about just prepending `uf_` to the beginning of the UF settings, but realized that some conflicts really do need to be reconciled. For example, if UF and Grav both provide a page title, there has to be some system in place to decide which one takes precedence, since keeping them both doesn't make sense.

My proposal to solve this issue is to provide a hook in UF where we can modify the settings before they're passed to Twig. That way, an adapter plugin can be written for any other application someone wishes to use with UF. The adapter can read the settings from UF and the third-party application (in this case, Grav), decide when to keep UF's setting and when to keep the third-party setting, and then give the modified settings back to UF to feed into Twig.

**Potential areas of concern:**
- We may need to always keep the third-party setting, since we won't have hooks in the third-party application to modify their settings (or maybe this doesn't matter since UF is the one initializing Twig?), but it's the only solution I could come up with to reconcile the conflicts.
- If an application is heavy-handed with Twig, they may end up wiping out any settings we've already set. For example, UserFrosting does this in `UserFrosting->setupTwig()` by wiping out all existing Twig template folders as part of its initialization. If another application does this with the globals, it may break UF regardless of what we try to do.

**Comment by r3wt** [comment]
i would be in favor of placing all of UF's globals in an array, and storing it in the global variable `uf` to me that makes much more sense, and the refactoring should be minimal.

**Comment by alexweissman** [comment]
I'm sorta working on this with the `Config` class in `/dev`.

**Comment by alexweissman** [comment]
Not sure if this is still going to be an issue with v4.  All of the Twig functionality has been moved to proper [`TwigExtension` classes](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/core/src/Twig/CoreExtension.php).

If there is any conflict, then it would simply be a matter of overriding or replacing this class.  Meanwhile, the [`Config`](https://github.com/userfrosting/config) class can be used to load values from configuration files without needing to set up the entire application.

I guess we can see if this is still an issue as we get closer to finishing v4.

**Comment by alexweissman** [comment]
OK so I've created [this plugin](https://github.com/userfrosting/grav-plugin-uf-adapter) for Grav that imports UF templates, config variables, and the UF asset manager.

The problem with placing UserFrosting config in a separate variable, is that Grav will still be looking for the `site` variable to have the content you want.  This might sometimes be the desired behavior, but for the most part you will want your "site title" to be reflected across all of the pages of your Grav site.  This means you would have to extend every single Grav template to use `uf.site` instead of `site`.

It's far easier if UF's `site` config values are merged into Grav's main `site` config values; in a way, that's the whole point.

As for templates, I've used [template namespacing](http://symfony.com/doc/current/templating/namespaced_paths.html) to allow you to explicitly reference specific Sprinkles, in addition to adding the templates to the main namespace.  You can also use the `twig.uf_last` setting to determine whether to load your UF templates before or after Grav's templates.

Anyway, take a look at it if this is still on your radar.  Open a new issue in the plugin repo if you have any further thoughts, comments, suggestions, etc.
