### ISSUE TITLE
Bootstrap not finding resource files.

### ISSUE THREAD

**Issue by Netrilix** [userfrosting/UserFrosting#503]
Bootstrap is currently looking in `/fonts` for the fonts it needs (see [here](https://github.com/userfrosting/UserFrosting/blob/161292fb9f57616cdadd44e667c12187a8b6f07f/public/css/bootstrap-3.3.2.css#L267-L272)), but its font files are actually stored in `/css/fonts` with FontAwesome's font files (since FontAwesome looks there for them).

Possible fixes are to store the fonts in two separate folders so both Bootstrap and FontAwesome can be updated without breaking anything, or to manually edit one or the other (point FontAwesome to `/fonts` or point Bootstrap to `/css/fonts`).

We're not really happy with either of these options, so if anyone has any other ideas, feel free to chime in.

**Comment by alexweissman** [comment]
We need an asset manager that can dynamically modify JS and CSS assets.

**Comment by alexweissman** [comment]
So I think the larger issue is, "how can we organize assets in the most logical manner, rather than having to put them wherever Apache/nginx expects to find them?"

For example, I'd like to see it possible to have assets grouped with specific themes (this would make it easy, for example, to provide a drop-in theme for Bootstrap 4).  

We also have other situations where assets need to be dynamically generated/modified based on some server-side information - for example, the paths to fonts, APIs, images, etc in JS and CSS.  Otherwise, we end up with problems exactly like this.

The problem with dynamically generating assets is that it will be [much slower](http://stackoverflow.com/questions/3697748/fastest-way-to-serve-a-file-using-php/3731639#3731639) because the PHP interpreter will have to be loaded for every asset request, putting a much bigger strain on the server.

I propose that we do something like Symfony's [Assetic](http://symfony.com/doc/current/cookbook/assetic/asset_management.html#dumping-asset-files), which dynamically generates assets during development, but then writes them to static files for deployment.  We could use Assetic itself, or code something up that works with [Stolz/Assets](https://github.com/Stolz/Assets).

**Comment by Netrilix** [comment]
I've opened a new issue, #504, to handle the asset manager, and I'm going to close this issue as soon as I add the temporary fix to hotfix 0.3.1.12.

**Comment by r3wt** [comment]
i use the following rules of thumbs:

all 3rd party libraries in `/dist` folder.
if subject has multiple files, it gets a folder, else file is placed in root folder (dist).

`
/dist
-- jquery.min.js
-- /font-awesome
-- /bootstrap
`

Maybe something like that could work here as well.

**Comment by Netrilix** [comment]
I like that idea. We'd still have fonts sitting in multiple folders, but it'd be very clear why if you look at the directory structure.

**Comment by Netrilix** [comment]
So are you saying we should keep each one entirely contained? So each complex addon would have its own `js`, `css`, etc folder? Or did you have a different layout in mind? (Just trying to expand on the layout you showed to see how it would look when you include all the files)

```
/dist
-- jquery.min.js
-- /boostrap
-- -- /js
-- -- -- boostrap-3.3.2.js
-- -- -- bootstrap-datepicker.js
-- -- /css
-- -- -- boostrap-3.3.2.css
-- -- -- boostrap-custom.css
-- -- /fonts
-- -- -- glyphicons-halflings-regular.eot
-- /font-awesome
-- -- /css
-- -- -- font-awesome-4.3.0.css
-- -- -- /fonts
-- -- -- -- fontawesome-webfont.eot
```

If this is the way you were saying, it has the benefit of keeping all related files together, but the multiple `/css` and `/js` folders feels strange.
