### ISSUE TITLE
API hook for password hashing, to fascilitate migrating from other systems.

### ISSUE THREAD

**Issue by AlexanderOMara** [userfrosting/UserFrosting#511]
Basically I'm looking to migrate an old-ish existing account system in the not-too-distant future, and I'm considering using this as the foundation for that system. I would like to preserve the existing user accounts as-is, the trouble is the password hashes, which are not in any of the formats used by this system.

Would it be possible to add an API hook somewhere to the core, where I can call-out to some plugin code to verify the password against my own legacy algorithms so that on first login users will still be authenticated, and their password hashes will be updated?

I see that `userfrosting/models/database/User.php` does something like this for it's own legacy password hashes, and it would be great if I could build off that without hacking on the core itself.

**Comment by alexweissman** [comment]
Ha, we were just talking about this very issue in chat today!  Yes you are correct, UF rehashes both its own legacy passwords, as well as any passwords encoded for UserCake (which I believe were SHA-1).

One of the more general issues we're trying to address in 0.3.2 (dev) is making it easier to add new code without modifying the UF core.  We're considering trying to do something like [Grav](https://github.com/getgrav/grav), where there is a core loader/environment object that provides a few hooks for developers to add their own code.  The situation is more complex with UF, though, because we're a fully database-driven framework/skeleton, as opposed to just a CMS (though Grav is a very good CMS!)  

My suggestion for now would be to extend the `User` class with your own class (for example, `class LegacyUser extends User`), and override the `login()` method to provide the functionality you need.  That way you're not directly modifying `User`.

**Comment by alexweissman** [comment]
Oh, I almost forgot to mention: [`class_alias`](http://php.net/manual/en/function.class-alias.php) would be a useful way to automatically use `LegacyUser` instead of `User` without changing code in the controllers.

**Comment by AlexanderOMara** [comment]
How would I use `class_alias` to use `LegacyUser` instead of `User`, if `LegacyUser extends User`? I've never used `class_alias` before, so I could be wrong, but it seems like it would prevent me from loading the real `User`.?

**Comment by alexweissman** [comment]
At the beginning of `initialize.php`, do:
`class_alias('UserFrosting\LegacyUser', 'User');`
(you might need to fiddle with the namespaces depending on how you define your class)

This will make it so that every time the PHP interpreter comes across `User`, it will substitute `LegacyUser`.  Since `LegacyUser` inherits from `User`, you will still get all the functionality of the original `User` class.

**Comment by alexweissman** [comment]
In v4, we should replace direct calls to `Password::` with the class mapper, so that someone can override the [`Password` class](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/account/src/Util/Password.php) and implement other types of hashing.
