### ISSUE TITLE
Using controller without making object each time

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#516]
Hi,

I have a question about dependency injection. 
Is there a way to use pre-allocated controllers like UserController and GroupController instead of creating new object? I guess Slim is a good tool for this but I am not quite sure where to create the first object and how to call it.

Thanks in advance

**Comment by alexweissman** [comment]
We're working on something like this in `dev`, using static methods.  It turns out that you can actually directly invoke static controller methods as a parameter in your route declaration: https://github.com/userfrosting/UserFrosting/blob/f2a2ee6c5022f4421d873badf5d9e3e3bc1c4901/app/routes/users.php#L8

**Comment by alexweissman** [comment]
This is solved in v4 ([`dev` branch](https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/account/routes/account.php)), using Slim 3's route binding feature:

```
$app->get('/about','UserFrosting\Sprinkle\Core\Controller\CoreController:pageAbout');
```

I believe Slim automatically creates the controller object and invokes the method this way.
