### ISSUE TITLE
$app->post('/jsonservice/?' not working

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#517]
Hi,

I am trying to send post data from 3rd party app to my website. Take a look at my code below:

In index.php

    $app->get('/jsonservice/?', function () use ($app) {  
        $data = $app->request->get();
        $controller = new UF\JSONController($app);
        $controller->Process($data);
    });   
    $app->post('/jsonservice/?', function () use ($app) {           
        $data = $app->request->post();
        $controller = new UF\JSONController($app);
        $controller->Process($data);        
    });

in test.html

    <html>
    <body>
    <form enctype="multipart/form-data" action="http://localhost/jsonservice/" method="POST">

        <input type="hidden" name="method" value="some_method" /> 
        <input type="submit" value="Send" />
    </form>
    </body>
    </html>

When I execute http://localhost/jsonservice/?method=some_method, it is perfectly working. In other words, seding GET data works.

But when I send the same data through POST form in my html file, the submitted page shows nothing. Why does the page show nothing and what was i wrong?

**Comment by Aterbonus** [comment]
Maybe the problem is you are not sending the crsf token. When you send a POST you must send this token or the request will be rejected.

Check the method "check" in [this file](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/middleware/CsrfGuard.php#L60-L111). 

UserFrosting use a [script](https://github.com/userfrosting/UserFrosting/blob/master/public/js/userfrosting.js#L80-L138) to send the forms and this script appends the crsf token to the request (This token is in the [`<head>`](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/templates/themes/default/layouts/layout-dashboard.twig#L20-Lundefined) tag of every page).

So, if this is the problem, you need to append the crsf token to the request manually (Like the script) or , if you send the data through a form rendered by twig, put this hidden input:
```html
<input type="hidden" name="{{csrf_key}}" value="{{csrf_token}}"> 
```

**Comment by Aterbonus** [comment]
Also, check [this issue](https://github.com/userfrosting/UserFrosting/issues/513).

**Comment by 9tontruck** [comment]
I guess csrf_token changes or expires once the session is reset. But I need to send post data from Android - once the app logs into the server, it has to be able to access to the server afterwards. Is there a way for Android app to communicate with the server without csrf token or with a long term token?

**Comment by alexweissman** [comment]
This is kind of an interesting scenario.  CSRF literally stands for "Cross-Site Request Forgery", and the [theory behind the token](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#General_Recommendation:_Synchronizer_Token_Pattern) is to prevent malicious agents from using a third-party site to trick users into performing an unintended action on your UF site.

However in your case, you actually *want* to allow users to perform an action on the UF site from another site (in this case, an Android app).  So, this presents an interesting challenge.  You don't want to just "switch off" CSRF for these routes, because then someone could exploit those routes in a CSRF attack.  

What you need is a way to get the token to the Android app.  Maybe, when the app logs into your server, the server can send back the CSRF token as a response?

**Comment by 9tontruck** [comment]
Thanks Alex.
The android app can get the csrf_token value of the login page of my website by just searching for 
<meta name="csrf_token" content="1bc05c9284e8...495a7709"> in the whole html code.
How do you think about this way?

If it works, what's the point of using CSRF token if a 3rd part app can grab the token value?

**Comment by alexweissman** [comment]
Well remember, there isn't *one* CSRF token - every session gets its own CSRF token.  So yes, a third party can obtain *a* CSRF token with the technique you described, but it can't obtain *the* CSRF token for the user it is acting on behalf of.  It can't even scrape the CSRF token by hijacking the client's session thanks to the [Same Origin Policy (SOP)](http://security.stackexchange.com/questions/94996/why-cant-you-steal-the-synchroniser-token-to-do-csrf).

So, your app would not be able to scrape the login page containing the user's CSRF token, because it would have to be either operating from within the user's browser (in which case it would get stopped by the SOP), or from outside the user's browser (in which case it wouldn't have access to the user's session).  Also, parsing the login page is very inefficient, and pointless when you could just create a new resource (route) that provides the CSRF token to the app in a JSON response.

What I would suggest is, rather than using UF's standard routes and CSRF token, you consider creating a new set of routes that are secured via an access token that is issued to the android app when it logs in.  Check out, for example, how Gitter's API works: https://developer.gitter.im/docs/authentication.  Since the access token is required to be sent in every request, there is no need for an additional CSRF token.

**Comment by 9tontruck** [comment]
Okay I got it. I actually created my own session_key table for that feature but I guess my work is kinda old style.
Thanks!

**Comment by alexweissman** [comment]
Nice, feel free to ask in chat if you have any more software design issues you want to discuss!

**Comment by 9tontruck** [comment]
Sorry for reopening this issue. Would you tell me how to get csrf_token value from $app? I can see the value in it when I do print_r($app) but it's hard to know how to retrieve the value.. :S

**Comment by 9tontruck** [comment]
The answer is $_SESSION['csrf_token'] 
Thanks!

**Comment by harding13** [comment]
@9tontruck could you explain exactly how do you solve this issue?

I think i got the same problem
