### ISSUE TITLE
csrf_token not working with Android

### ISSUE THREAD

**Issue by 9tontruck** [userfrosting/UserFrosting#521]
Hi,

I was facing a weird problem when my android app tries to access the server.
In android app, csrf_token keeps changing everytime it tries to access the server which means downloaded csrf_token expires right away.

After deep research on this, I found out the old session style csrf does not work Android app anymore. Does anyone know how to overcome this problem?

**Comment by alexweissman** [comment]
Do you mean the way we figured out in [#517](https://github.com/userfrosting/UserFrosting/issues/517#issuecomment-184377424)?

**Comment by alexweissman** [comment]
@9tontruck did you ever find a solution for this?  I'd like to take this into consideration for the design of UF 4.  

It seems to me that since [CSRF is a social engineering attack on a user's browser](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)#How_does_the_attack_work.3F), an Android app, as a "browserless" client of the UF app, would not be susceptible to such an attack and thus UF could safely bypass the CSRF token check for the app's requests.  If this is the case, we just need to provide a mechanism for bypassing the check on certain POST requests.

However, I am probably out of my depth since I am neither an Android developer nor a security expert.  This seems like it would be a good question for https://security.stackexchange.com, if generalized appropriately (for example, "For what types of clients and requests is CSRF mitigation required?")

**Comment by alexweissman** [comment]
Further discussion about providing a way to bypass CSRF for individual routes in #513.
