### ISSUE TITLE
Create Group from Display Name at Register

### ISSUE THREAD

**Issue by jamiegamauf** [userfrosting/UserFrosting#523]
I would like a group to be created at the time a user registers on the site or at least when they activate their account.

I would use the display_name as the Group name and have the same default settings for all.

My thought is a company registers on the site and their company name is the group.  They would not belong to any other groups.

**Comment by alexweissman** [comment]
Shouldn't be too hard.  Take a look at the code for [user registration](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/controllers/AccountController.php#L295-L454), as well as that for [group creation](https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/controllers/GroupController.php#L214-L305).  You'll modify user registration to create a new group and add the user to it, rather than adding the user to the default groups.  You might want to do this as a [transaction](https://laravel.com/docs/5.1/database#database-transactions) so you don't end up creating the group if user creation fails.

You'll need to set some default values for the new group's icon, landing page, theme, etc.

**Comment by alexweissman** [comment]
Let us know if you are still having trouble with this!
