### ISSUE TITLE
Is it time to bring UF out of beta?

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#546]
Up until now, we've been using `0.*` for our versions - mainly to signify that UF is a "work in progress".  However at this point, we have over 500 stars and a thriving community of developers who are using UF successfully in real-world projects.

Is it time to bump us up from `0.*` in the next major version?  Either we could increment sequentially to `1.0`, or we could drop the leading `0` entirely and have version `4.0` (`0.3.1` => `3.1` => `4.0`).

**Comment by Netrilix** [comment]
I'd definitely be in favor of coming out of beta. We'll need to come up with a solid list of bugs that aren't acceptable in a finished product (there are only 66 open issues, so we probably won't find too many that are critical - #497 comes to mind if we don't end up switching to Monolog before leaving beta).

As far as version numbering goes, dropping the leading `0` sounds good to me. I don't particularly like the sudden jump from `0.3.1` to `4.0`, but it'd cut down enough confusion that I think it's worth it. I wouldn't touch `3.x` at all, since currently everything in `0.3` is beta, so starting with `4.0` would probably be our best bet for a release version.

I won't put up a fight for that one though. Having `1.0` be our release version sounds much more tempting; I'm only shying away from it because of the potential for version confusion.

**Comment by alexweissman** [comment]
So, I guess I should clarify what I mean by "beta".  I'm thinking that we're nearing the end of "design beta", where we've been playing wildly with the overall architecture of UF - for example, dropping and adding major components, getting up to speed with PSR, etc.  Subsequent versions will always have their own betas, but I think we're now at the point where we can say that most of the huge, fundamental design questions have been figured out.

**Comment by Netrilix** [comment]
Yeah, that definitely makes sense. But if we're going to start using non-beta numbering, we're probably going to want some kind of stable vs. experimental designation, right? So if someone is looking to start a site today on a version, we know exactly which version to point them to that's been heavily tested? (Right now we've mostly been pointing them to the `dev` branch, which somewhat goes against our "best practices" goal)

**Comment by alexweissman** [comment]
We could just do something like what Slim does with its [releases](https://github.com/slimphp/Slim/releases?after=3.0.0-RC2), using "beta" and "release candidate" where appropriate.

**Comment by Netrilix** [comment]
Yep, that'd definitely work.

**Comment by alexweissman** [comment]
Alright, I hereby decree: the next version will be called "4.0".
