### ISSUE TITLE
Considerations for assets in v4

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#560]
There's been a lot of hubbub about three related topics:
### Separating developer and core code

This is the biggest one.  To build a site with UF requires the developer to directly change the code that ships with the initial installation.  This makes it harder to upgrade in the future, even when using `git merge`.  Also, I've found certain applications where I actually want to _remove_ some functionality from UF.  For example, sometimes I create a purely public site, and I need to strip out all of the authentication and account management features.   
### Theming

To me, this means a drop-in package of custom styling and templates.  Themes could be applied to an entire site, or be customizable for different groups/users.  We sort of have this right now, but it is fairly limited in what it can do.  For example, all custom CSS has to go into a single CSS file, and a theme can't incorporate its own client-side code.
### Plugins

A drop-in package of code that implements some functionality.  For example, we have the OAuth and thumbnail plugins.  They rely on an awkward combination of hooks and inheritance to function properly.

---

**What these all have in common**, is that they are all self-contained module that should require no modification of the base code.  My idea is to generalize these three types of modules to be handled by the UF application in the same way, which we are calling _sprinkles_.  Thus, developer-contributed code, third-party plugins, and themes would all be types of sprinkles, and placed in subdirectories under the `/sprinkles` directory.

This brings us to the subject of **assets**, i.e. CSS, Javascript, image files, and other media files.  I've developed the [userfrosting/assets](https://github.com/userfrosting/assets) package, which can generate the appropriate `<style>` and `<script>` tags from a [JSON schema](https://github.com/userfrosting/UserFrosting/blob/dev/build/bundle.config.json).  However, I am not sure if this fully meets the needs of all possible use cases for sprinkles.  Consider the following use cases:
- A sprinkle should be able to contribute assets to site pages - both those pages managed by the sprinkle itself, but also any of the "core" pages.  This is essentially the behavior people associate with "theming".
- A sprinkle should be able to _override_, _replace_, or _remove_ assets from the core or other sprinkles.  For example, we could imagine a sprinkle that replaces the default `bootstrap-3` with `bootstrap-4`.
- In the case of themes, it should be possible to dynamically select certain theme(s) at runtime.  For example, group- or user- specific theming.
- The "effective assets", i.e. those that will actually be active on the site once all overrides/replacements/removals have been resolved, need to be compiled and placed in the `public/` compiled asset directory.  Note that in the case of dynamically selected themes, there will need to be a compiled version of each possible theme's assets. 

I would like to hear everyone's thoughts on these use cases.

**Comment by frostbitten** [comment]
### Separation of code
One solution to this might be to separate the core of UserFrosting into a configurable package, to be loaded from the `/vendor` directory. Additionally (and this would be the defacto solution for most) the developer could download a *basic app template*. This *basic app template* has all the necessary folder structures, an app.php/config/etc, and perhaps even some empty classes that `extend` the core (with no additional functionality).

The `core` in this idea would contain all of the default routes/templates/models that regard the current dashboard. Basically, it's everything except configurations and the implementations.

### Theming
One other thing I believe needed by themes is the ability to run a bit of php code. For instance, if it requires a custom twig function.

On assets, I haven't tried the assets manager yet but from the sound of it it seems to have the necessary functionality. I've been used to generating assets on demand and it has worked well, but generating them all ahead of time (for production) would seem fine.

On how to actually deliver the different assets types, I'm not sure. There are some cases where an app might want all assets bundled at once. There are also times when there is a common set of assets shared across all pages with certain pages that load more. In this latter case it would seem unwise to bundle the common set of assets with the (sometimes just one) extra assets. Rather, I'm thinking we need something that separates each asset group/collection into individual minified files. So, we'd end up with `common.min.js`, `common.min.css`, `root-flavor.min.css`, `nyx-flavor.min.css`, etc (where the flavors have only their custom styles). This should make delivering varied assets a bit faster with only a few additional requests per page. (Trade more requests for less transfer). Google doesn't shun websites having more than one css or js file, it's when you have too many that it begins to impact PageSpeed.

I see css/js assets being defined by all the places a user is allowed to go. If they may end up there, they should have already loaded the necessary code. If they have been explicitly denied access to certain features, it doesn't really matter if they can see the code for such features within the css/js. The real authority is server-side.

**Comment by lcharette** [comment]
Don't forget that plugins should also be able to comes with specific locale files for multi languages sites.

As for shared assets, I usually let the template take care of it (and minify files manually myself) since one template could use one framework and the other template another framework. Shared assets could also be placed in a "all/" directory that can be used with any template.

Like I told you before, I come from phpBB word. They did a really nice job with extensions in version 3.1 ([See here](https://www.phpbb.com/extensions/writing/)). You basically drop the extension folder in the ``ext/`` folder and voilà! Could be inspiration for UF.

They solved the ressources overlap problem using a simple test and define tag (See "Including JavaScript and CSS Scripts" in above link)

**Comment by Netrilix** [comment]
I'm still taking time to think all of this over, but I had a quick thought that I wanted to put to ink before it left my mind. If we allow sprinkles to override each other, should we have some sort of system for precedence? In the type of system you're talking about, loading order is going to become very important. For example, if a chocolate sprinkle and rainbow sprinkle override the same `.css` file, we'd need the developer to be able to easily decide which one to favor, right?

**Comment by lcharette** [comment]
The question we need to ask ourselves is how often one resource will be overwritten? It’s not worth it if it’s one specific use case… But in the long run, it could be a problem indeed, at least with sprinkles not updating to new framework versions.

I see 3 cases: css, javascript and frameworks.

For Frameworks (Jquery, FontAwesome, Angular, etc), we could assume JQuery and FontAwesome are always there. In other cases, dependencies management could be a simple solution. For example, if my sprinkles requires Angular, I make it dependent on the Angular sprinkle. This take care or versioning, but again simple ``if`` would do the trick if we don't care about versions.

Regular js files (like ajax & form manipulation) should either be theme specific (mobile theme doesn’t behave the same way than desktop theme for example), so handled by the template in it’s own directory, or work with any templates (no template specific selector in the js code) and be located in a "shared" directory (``all/`` template or ``Assets/`` top level folder). Second option always the best.

For css, I think it's simpler if each sprinkle use it's own css/theme file association. A filename convention based on the sprinkle name could be used to avoid overlapping. But this comes at the cost that more than one css file would be loaded by the browser. Maybe a custom Twig function could be used to include css and js and combine them on the fly or at least include the ``<script>`` tag at the right place.

The thing is since themes are not in the public folder, the assets are currently separated from the themes directory, making it difficult to associate assets (mainly css) with themes…

**Comment by alexweissman** [comment]
The only thing left to do on this is implement user themes, and this is discussed in #597.
