### ISSUE TITLE
Email address as username only

### ISSUE THREAD

**Issue by m0lmk** [userfrosting/UserFrosting#569]
Feature request.

There is already an option to allow the use of an email address as a username but can there be an option to disable the username requirement completely and just use the email address?

When this setting is activated it should remove the "Username" field on the registration form and set all "Username" inputs (like on the login form) to "Email Address".

**Comment by pengimo** [comment]
I've seen where the original feature was implemented here...

https://github.com/userfrosting/UserFrosting/issues/4

So can it be expanded to make the UI a bit better by removing the "Username" field completely in the registration form (change it to a hidden field that populates with the email address upon submit maybe or just populate the var with the email address upon submit?)

Then it's just the phrase "Username or Email" that would need updating on the login form.

**Comment by alexweissman** [comment]
Ref #495.

For UF 4, I would like to find out how often people actually need "username" in their applications at all.  

It is definitely useful as a pseudo-anonymous, non-sensitive handle for allowing users to identify one another within an application, but of course there are many applications where users do not interact with one another at all.  I agree that in these applications, a username might be unnecessary.

So, the question is whether username should be a default field, or something that devs should just add if they need it.

**Comment by alexweissman** [comment]
And no, I do not want to make something like this a configurable option.  The extra logic necessary would just be clutter with a design decision like this, which is "set-and-forget" for any given application.

**Comment by leecollings** [comment]
PErsonally, I would remove 'username', and use email address for all account related logins/sign ups etc.

Then have a setting called 'Display Name' for that user, to be referenced when logged in, or anywhere else on the site.

**Comment by alexweissman** [comment]
After more thought and work on UF4, I've concluded that we do need some sort of "username", at the very least to act as a URL-friendly "slug".  For example, perhaps I want to access a user's account info page using their username (instead of an id):

`http://example.com/users/u/alexweissman`

Now, one possibility is to do something like what Stack Overflow does, and automatically generate a username from a chosen display name.

**Comment by leecollings** [comment]
Maybe just implement email only for authentication then, and leave username for the slug, and then a friendly 'Display Name' like Wordpress allow you to select?

**Comment by alexweissman** [comment]
Ok, it's an interesting idea.  Let's pin this for v4.1.

**Comment by pengimo** [comment]
I like the suggestion Lee made. Seems like a good way forward.

**Comment by alexweissman** [comment]
I have developed a compromise, so that we can still have unique, friendly usernames for URL slugs but without creating unnecessary obstacles to registration.  The default registration interface will try to automatically generate a username from your first and/or last names.  It will instantly validate the username to make sure that it isn't taken.

If the username you want/get autogenerated isn't available (for example, if you have a common name), then you can either enter a username manually, or use the "suggest" button to generate an adjective-noun phrase for your username.

Try it out at https://demo.userfrosting.com and let us know what you think.

**Comment by leecollings** [comment]
I don't see the point of the Suggest button,  if it's going to suggest something completely unrelated to what you're trying to do.

If ideally, you want the username to be a form of the users name, then stick with that, and possible just add a sequential number on the end if the initial firstname.surname is already taken.

This is the most common use for this kind of thing isn't it? I Don't think the suggest button is needed.

**Comment by alexweissman** [comment]
The problem with sequential numbering, is that it makes account enumeration attacks really easy.  If it suggests to me leecollings76, then I know that there are probably leecollings, leecollings1, ...

Plus, maybe the suggestions are a little more memorable, for situations where the site functions depend more heavily on the username?

**Comment by Arifi** [comment]
Yeah i agree with leecollings.. it's not really worth..
