### ISSUE TITLE
Customizing default userfrosting.js file may lead to (hard to detect) error

### ISSUE THREAD

**Issue by amivag** [userfrosting/UserFrosting#589]
Hello,

(Apologies in advance, if this is just programming incompetence on my part.)

I edited userfrosting.js to insert a new function call to a function in another part of the program. More specifically, in the ufFormSubmit function, in the submit handler function.... I added a simple function call like so: 
`myUndefinedFunction();`

myUndefinedFunction works ok for the logged in user, but by mistake, it was not defined in the log-in area. The result was that in trying to log-in, the following side-effects occur:
- URL changes to "/account/login" (instead of going to /dashboard)
- White blank page
- No error logs, not in php, not in browser console. 

It was simple to fix, but hard to find out that the cause was an undefined function.

How can we safeguard against these kinds of errors, where everything stops working, with no causal hints whatsoever?

Thank you.

[userfrosting 0.3.1]

**Comment by alexweissman** [comment]
So what you're saying is that Javascript errors basically silently break everything?  This happens in other situations as well, for example with [CSRF token errors](https://github.com/userfrosting/UserFrosting/issues/513).

So, Javascript was failing because of an undefined function `myUndefinedFunction`, but then it didn't raise any errors in the browser console?  Is it because `myUndefinedFunction` is passed in dynamically as a callback?

At any rate, v4's [form submission plugin]((https://github.com/userfrosting/UserFrosting/blob/b48f29eae3a62b235a00f982dbf9f80fd1c03c23/app/sprinkles/core/assets/js/uf-form.js)) uses events instead of callbacks.  Do you think that will solve your issue?

**Comment by Endroe** [comment]
Thank you!!! I was stumped, getting a blank page whenever anyone logged in. No error logs, nothing. Please document this somewhere so others don't get the same issue.

**Comment by alexweissman** [comment]
There's an [article in the wiki](https://github.com/userfrosting/UserFrosting/wiki/On-the-matter-of-CSRF-tokens), but since this is such a common issue, we could add it to the "troubleshooting" page as well.

At any rate, this should be a moot issue in v4.
