### ISSUE TITLE
Problems with Tutorial 2

### ISSUE THREAD

**Issue by Xcelsus** [userfrosting/UserFrosting#602]
actually I installed UF on my PC so when i was doing the tutorials, the number two, to be precise, I noted an error that says HTTP ERROR 500.
I'm using XAMPP maybe doing it in a local environment is making the problems... So if anyon can help me with this i really apreciate this

**Comment by Silic0nS0ldier** [comment]
A HTTP 500 error can be just about anything. You'll want to have a look at the Apache error log (accessible via XAMPP Control Panel by clicking on `Logs` and then `Apache (error.log)` in the `Apache` column).

From the log, you should be able to gleam more info on what's causing the issue. If not, share what's in your log, and from there we should be able to pinpoint what happening.

**Comment by Xcelsus** [comment]
well thanks for the tip... i check the error log and there two lines that i believe are conected with this error
`[Sat Dec 10 14:39:27.228563 2016] [:error] [pid 2280:tid 1712] [client ::1:56301] Error in C:\\xampp\\htdocs\\userfrosting\\userfrosting\\controllers\\GroupController.php on line 481: Undefined index: group_id
[Sat Dec 10 14:39:27.229569 2016] [:error] [pid 2280:tid 1712] [client ::1:56301] #0 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\controllers\\GroupController.php(481): Slim\\Slim::handleErrors(8, 'Undefined index...', 'C:\\\\xampp\\\\htdocs...', 481, Array)\n#1 C:\\xampp\\htdocs\\userfrosting\\public\\index.php(76): UserFrosting\\GroupController->updateGroupTitles()\n#2 [internal function]: {closure}()\n#3 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\vendor\\slim\\slim\\Slim\\Route.php(468): call_user_func_array(Object(Closure), Array)\n#4 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\vendor\\slim\\slim\\Slim\\Slim.php(1357): Slim\\Route->dispatch()\n#5 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\vendor\\slim\\slim\\Slim\\Middleware\\Flash.php(85): Slim\\Slim->call()\n#6 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\vendor\\slim\\slim\\Slim\\Middleware\\MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#7 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\middleware\\CsrfGuard.php(51): Slim\\Middleware\\MethodOverride->call()\n#8 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\middleware\\usersession\\UserSession.php(27): Slim\\Extras\\Middleware\\CsrfGuard->call()\n#9 C:\\xampp\\htdocs\\userfrosting\\userfrosting\\vendor\\slim\\slim\\Slim\\Slim.php(1302): UserFrosting\\UserSession->call()\n#10 C:\\xampp\\htdocs\\userfrosting\\public\\index.php(430): Slim\\Slim->run()\n#11 {main}`
I hope someone can understand this and give some light on this problem

**Comment by lcharette** [comment]
Can you tell us which version of UserFrosting you're using? In the database, does the `group_id` column exist in the group table ?

**Comment by Silic0nS0ldier** [comment]
Presumably at line 481 in `GroupController.php` you have the following line.
`$users = User::where('primary_group_id', $post['group_id'])->get();`

If I had to guess, I'd say that the `group_id` isn't being submitted. Go have a look in `group-titles.twig` and make sure `name` attribute for the group drop down is set to `group_id`. Its also worth checking the validation schema (`group-titles.json`) to ensure it matches the one in the tutorial.

@lcharette In tutorial 2, its getting the form data from `$post` variable rather than `$data`. Isn't the latter meant to be used as it's been properly filtered and sanitized server-side?

**Comment by lcharette** [comment]
Oh. Yeah, right. You should probably come over to [the chat](http://chat.userfrosting.com) then.

**Comment by Xcelsus** [comment]
first of all... i wanna say thanks to @lcharette and @Silic0nS0ldier for take his time and help me with this.

1. i was checking the group table and there is not a `group_id` it's just `id`
2. there is no line 481 in GroupController.php but i will find the line that you write in the post and try to deduce what is wrong

**Comment by Silic0nS0ldier** [comment]
Sounds like you've edited your code since the error was thrown. (hence line 481 not existing)

I think your best option with this is to grab a fresh copy of the UserFrosting source code, and attempt tutorial 2 again. Its fairly easy to miss something.
However, if you've made changes you don't want to loose, your best bet is to read through tutorial 2, while at the same time ensuring that your code matches the tutorial.

**Comment by alexweissman** [comment]
Please feel free to re-open if it turns out that there is an error in lesson 2.
