### ISSUE TITLE
Exception on user login via AccountController

### ISSUE THREAD

**Issue by RomeroMsk** [userfrosting/UserFrosting#644]
Using `$authenticator->attempt()` in `UserFrosting\Sprinkle\Account\Controller\AccountController::login()` makes it throw an exception and return the `500` HTTP status in case of invalid credentials or blocked/unverified user. It will be better to return the `401` HTTP status in such cases, as it is not an "internal server error".

**Comment by alexweissman** [comment]
You need to set `displayErrorDetails` to `false` in your config file.  This should cause the exception handler to kick in and return the appropriate status code.

**Comment by alexweissman** [comment]
See https://learn.userfrosting.com/error-handling/overview#debugging-modes for more information on this feature.

**Comment by RomeroMsk** [comment]
Ok, got it. But after setting this conf to `false` I'm getting `403` (Forbidden), but it should be `401` (Unauthorized).

**Comment by Silic0nS0ldier** [comment]
HTTP Authentication isn't used, so 403 is the correct status code.

**Comment by RomeroMsk** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

> 10.4.4 403 Forbidden
> 
> The server understood the request, but is refusing to fulfill it. Authorization will not help and **the request SHOULD NOT be repeated**.

But nvm, I will override this controller anyways.

**Comment by Silic0nS0ldier** [comment]
Again, UserFrosting does not use **HTTP-Authentication**, as such 401 is wrong for the context, since there would be no WWW-Authenticate to provide. (the latter of which is required for 401)

**Comment by RomeroMsk** [comment]
I understand your arguments.

**Comment by alexweissman** [comment]
Actually, no need to override the `Authenticator` class if you want to return a different sort of response.  Simply create your own [custom handler for the relevant exceptions](https://learn.userfrosting.com/error-handling/overview#registering-custom-exception-handlers), register them with the exceptions in your service provider, and have them return the status code you want!

**Comment by alexweissman** [comment]
Btw, I wrote guidelines for 401 and 403 responses: https://learn.userfrosting.com/routes-and-controllers/rest/restful-responses#401-unauthorized.  

In the case of `AccountDisabledException`, I do think a 403 response makes more sense.  403 means "we know who you are, but you do not have permission to do this thing."  So, if your account has been disabled, you've effectively had _all_ of your permissions removed.

In the case of `InvalidCredentialsException` and `AccountNotVerifiedException`, I'm not really sure.  They're both saying "hey, you're not allowed in here because we don't know who you are".  I.e., you still need to take some additional steps.  It's hard to say if a 401 would be more appropriate, or perhaps even another status code entirely.  One could argue that invalid credentials, for instance, constitute a "malformed request" and should return 400.

**Comment by RomeroMsk** [comment]
> Actually, no need to override the Authenticator class if you want to return a different sort of response. 

I didn't say that I'm going to override the `Authenticator`, I just added my own controller to handle AJAX requests and return status codes that I want + JSON data in response body.

**Comment by alexweissman** [comment]
Ok.  I'm just saying, you don't even need to do that in your controller.  All of that could be done through a custom exception handler.
