### ISSUE TITLE
Providing Authorizer with disordered parameters in an permissions check can result in a false positive.

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UserFrosting#652]
An issue has been discovered in the `Authorizer` where providing incorrectly ordered parameters to `checkAccess` can result in a false positive result.

Can be replicated easily via the twig extension `checkAccess` as follows.
```twig
{# Testing using permission that doesn't exist #}
{% if checkAccess(currentUser, 'permission_slug') %}
False positive, this shouldn't be output.
{% else %}
What should be output.
{% endif %}
```

Under PHP 7.0.15 and IIS 10, this only triggered warning and notice level errors.

**Comment by alexweissman** [comment]
Oh!  Yeah some type-checking would be a good idea.

**Comment by alexweissman** [comment]
Ok, I figured out what is going on.  Basically, the `User::permissions()` relationship is used to load all of a user's permissions that match a given permission slug - IF a slug is specified.  If you pass a falsey value to this relationship, it defaults to load _all_ of the user's permissions instead.  See https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Model/User.php#L329-L355

When you added that erroneous `currentUser` parameter to your call to `checkAccess` in Twig, all the parameters get pushed back one place, and `currentUser` is used as the slug instead of the actual slug name.  Somehow, the `currentUser` object you're passing into Twig is then being cast to a falsely value.  So when `AuthorizationManager` calls the `permissions` relationship on that falsey value, it ends up retrieving ALL the user's permissions instead of just the ones for that slug.  Assuming the user has even one valid permission for the entire application, this causes a false positive.

Honestly, I'm not too thrilled with the current implementation of the `permissions` relationship anyway.  Also, the fact that `checkAccess` invokes the relationship every single time, means that an insane number of queries are being executed on each page load (see #612).  If we just load all user permissions once, and then check for the slug in PHP rather than by doing a separate query each time, we'll fix this bug and greatly improve performance.

**Comment by Silic0nS0ldier** [comment]
If it's down to bad input for `currentUser`, type checking would serve as a good hotfix. Does PHP 5.6 support built in type checking? Would make for a nice and clean implementation is it does.

**Comment by Silic0nS0ldier** [comment]
And yes, https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Model/User.php#L329-L355 is a horrible query.
I did however manage to build a more readable version over at https://github.com/Silic0nS0ldier/UF_OIDCAccount/blob/master/src/Model/User.php#L91-L97, not that I've had the chance to properly test it.

**Comment by alexweissman** [comment]
Well, it might be a good chance to use my new `BelongsToManyThrough` custom relationship ;-)

**Comment by Silic0nS0ldier** [comment]
Maybe... maybe... I take that it spits out the same sort of query in the end?

**Comment by alexweissman** [comment]
Pretty much.  I need to figure out which one would be more efficient for this specific purpose.

**Comment by alexweissman** [comment]
Fixed.  See https://github.com/userfrosting/UserFrosting/commit/706cbe361f17bda0169b86a3d1606dc02a2786aa and https://github.com/userfrosting/UserFrosting/commit/66aae5040032dfdfa956af65a4a88f19f12bb98e.
