### ISSUE TITLE
Hardcoded redirect to `dashboard`

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#680]
See #677.

By default, every role has _some_ sort of access to the dashboard page, but the problems is a user might not have access to the dashboard if the dev change that behavior.

The redirect link should be defined in a `RedirectHandler` class or something like that which people can override as needed, similar to the redirect after login.

**Comment by splitt3r** [comment]
This thing is really annoying 👎. We have removed the `uri_dashboard` right from the default group and now resetting the password leads to an error page because of https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Controller/AccountController.php#L583 this.

**Comment by alexweissman** [comment]
ok, we can try to prioritize this.

**Comment by alexweissman** [comment]
How about, instead of the hardcoded redirect, we have a `redirecter` service that creates and returns a new `Redirecter` instance.  The `Redirecter` class will have a method `toDefaultPage` or something, that performs the redirect (by default to `/dashboard`).

Sprinkles could define their own `Redirecter` child classes and override the `redirecter` service to use their custom class.  We could define an interface that all `Redirecter` classes must conform to.

The `determineRedirectOnLogin` service could also be subsumed into this class, which would now be responsible for handling all sorts of redirect scenarios.

**Comment by splitt3r** [comment]
Sounds good to me 👍

**Comment by alexweissman** [comment]
Alternatively, this might be an appropriate use of [events](http://symfony.com/doc/current/components/event_dispatcher.html).  We could have `alreadyLoggedIn` and `redirectOnLogin` events, with a custom subscriber that handles these events.

The only problem is that to override UF's default handlers for these events, you'd have to mess around with event priority numbers and `stopPropagation()` to make sure that only your Sprinkle's handler is invoked (there can be only one!)

Depending on how you look at this, this could be a feature or a pain in the ass.

**Comment by alexweissman** [comment]
Ok, take a look at what I've pushed to branch `feature-redirecter`.  Basically, the idea is that you would write your own `Redirector` class that extends `UserFrosting\Sprinkle\Admin\Http\Redirector`, and then override the `onAlreadyLoggedIn` method to handle the redirect as you see fit.  Then you would extend the `redirector` service in your service provider to return an instance of your custom `Redirector` class.

Not sure how this would play out in community Sprinkles since you have to extend the entire `Redirector` class.  I guess that's one potential benefit of using events instead.

**Comment by alexweissman** [comment]
Actually when I think about it more, maybe this is just unnecessarily complicating things.  It might be sufficient to go back to letting each action correspond to its own service, and then Sprinkles can directly override individual action-services as needed.

**Comment by splitt3r** [comment]
I will have a closer look at it by the end of next week 😀

**Comment by alexweissman** [comment]
I think I'm gonna go with simple services after all.  They're easy to override as needed, without worrying about fighting with other Sprinkles over a dedicated class or event listeners.

The one thing I've done is to group these redirect-related services by prefixing them with `redirect.`.  So now we have `redirect.onLogin` and `redirect.onAlreadyLoggedIn` services.
