### ISSUE TITLE
Encapsulate migrations and migration manager into classes

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#683]
Install script is a [procedural hot mess](https://github.com/userfrosting/UserFrosting/blob/master/migrations/install.php#L121-L151).  This should be factored out into a proper `MigrationManager` class.  

Also, migrations for each Sprinkle should be encapsulated in a `Migration` child class.  I propose that we follow [Laravel's pattern](https://laravel.com/docs/5.4/migrations#migration-structure).

**Comment by Silic0nS0ldier** [comment]
The concept of migrating 'up and down' is neat, but there are plenty of cases where migrations will be one-way. Food for thought.

**Comment by lcharette** [comment]
Also, a migration file should be wrapped inside a transaction. If the file have 3 tables to create and fail at the creation of the second one, we don't want to end up with a partial migration. More so if the migration successfully create a table, but fail when inserting default values.

**Comment by colinmollenhour** [comment]
@lcharette DDL updates cause implicit transaction commits so you can't create multiple tables within a single transaction or even create a table and insert into it in a single transaction. So, it probably makes sense to just depend on the user to use transactions in their migrations as needed.

**Comment by lcharette** [comment]
Yeah I figured that out when working on my unit tests, as the temp table wasn't being rolled back. Table creation could be "manually" rolled back using `up` and `down` migrations thought.

**Comment by lcharette** [comment]
This might be a helpful read : https://siipo.la/blog/how-to-use-eloquent-orm-migrations-outside-laravel

**Comment by alexweissman** [comment]
Hmm, so what exactly do we get from Phinx?  Just the `AbstractMigration` class that we can extend?

**Comment by lcharette** [comment]
Not sure really. I had this in my notes... Might not be useful since we do have an "app" that can be used to run the migration. It's probably more useful when you have nothing.

**Comment by lcharette** [comment]
To define the migration order, Laravel uses timestamps. We used version number (unrelated to the core UF version numbers) in 4.0. Which one you think is the best? 

Plus, we uses one migration file for all tables while laravel uses one per tables. Do we need one migration per table?

FYI, Great text on how Laravel migration works: http://stackoverflow.com/a/39484232

**Comment by Silic0nS0ldier** [comment]
I'm leaning more towards the existing version numbers system. If only because it semantically conveys more information.

For example, suppose a migration performs several drastic changes.
(laravel)
01-04-2017.php
27-04-2017.php
(current)
1.4.2.php
2.0.0.php

With a version number based system, major changes can much more easily be identified. (which can also help with debugging)

**Comment by lcharette** [comment]
Yeah that's right, but at the same time if there's a big breaking change in the db, it should comes with a version bump in the code/github repo too. 

Using version number will also be easier to migrate from `4.0` to `4.1`.

**Comment by lcharette** [comment]
I'm starting to get why Laravel uses dates...

First issue, since migrations files will now be _classes_, we need to autoload them. This means we can't use the `4.0.0.php` convention anymore. Best bet so far would be to use `V4_0_0_Migration.php`, similar to what Laravel is using. Adding the `V` at the beginning means we can autoload that class instead of manually requiring it like Laravel does.

Other issue, since the `4.0` migrations are stored in the db with the `4.0.0` version format, it will be difficult to compare to the `4_0_0` format. This is not really an issue with core tables (no other version than 4.0.0) but it could be for other sprinkles (like mine).

This also means a big breaking change for next version...

**Comment by lcharette** [comment]
I checked other frameworks (that uses db) to see how their migration system was done. Funny how a project like _Zend Frameworks_ doesn't have a migration tool built in. 

On interesting example is (my old pall) phpBB. Pre v3.1, all the version where in one big file and all the versions were listed in a big array. From version 3.1 and later, the whole base code was rewritten in modern standards and based on Symphony. Long story short, their migrations are organized between core and extension migrations and the namespaces are formatted like `phpbb\db\migration\data\v310\something`. 

[See their doc](https://area51.phpbb.com/docs/dev/32x/migrations/getting_started.html) and also how the repo is organized between version and prerelease migrations: https://github.com/phpbb/phpbb/tree/master/phpBB/phpbb/db/migration/data

I do like the `v310` part, better than the proposed `V3_1_0` we talked here and on the chat... Would still work with the old version naming scheme, as we would just have to strip the `.`... 

Plus, their migration dependencies (See [`depends_on`](https://area51.phpbb.com/docs/dev/32x/migrations/dependencies.html)) might be worth looking into this. From what I understand, this dictate which migration will be run first. If Migration `A` is to be run first, but it depend on `Z`, Then the script will load `Z` before applying `A` and won't try to reapply `Z` when it get to there (because it know it already been run).  So that takes care of the order (as long as `Z` doesn't require `A` to be installed first).

**Comment by colinmollenhour** [comment]
What's wrong with the current system? The only change I would make is to move the save inside the loop so that the update is checkpointed after each successful script instead of just once at the end. Also as a convention to keep the files scoped mostly for IDE friendliness you could wrap the file contents with an anonymous function like is common in jQuery. But, if you really want to make it OO I'd recommend Phinx.

**Comment by lcharette** [comment]
I looked into Phinx. It's great, but mostly useful when you don't have an application stack behind to run your migrations. We have the core UF function we can use, so Phinx is not really useful (no added value).

The migration file will now be wrapped in classes. Current plan is also to support rolling back a migration, which will help a lot while working on code. Migrations dependencies, based on my previous post, will also be added to help with structure integrity and not have [the whole db migration in a single file](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/migrations/4.0.0-alpha.php).

You can check the current progress in the `develop` branch and the [CLI project dashboard](https://github.com/userfrosting/UserFrosting/projects/1).

**Comment by colinmollenhour** [comment]
I really wouldn't bother with rollback.. There are so many situations where you can't rollback and I've never once seen this used in a useful way (or at all). For development you can simply take a snapshot and restore the entire snapshot with a two-line script.

**Comment by lcharette** [comment]
@colinmollenhour Rollback is useful when testing a new migration. It will also be useful in case of UF if you need to delete a sprinkle.

New migration tool is mostly done in the `develop` branch now. Need some review of the code. Maybe some improvement here and there. I'll document soon.

Usage: `composer run-script migrate`
To rollback latest migration : `composer run-script migrate:rollback`

**Comment by Silic0nS0ldier** [comment]
@lcharette Not so much for testing. If something goes wrong during testing of a migration, you typically can't undo it. The use case could be experimenting with different database models, etc. But definitely not migration testing.

**Comment by lcharette** [comment]
That's what I meant;)

**Comment by lcharette** [comment]
This is done in `develop`. I just need to document the whole thing

**Comment by lcharette** [comment]
This is now done and documented in the develop branches of UF and Learn.
