### ISSUE TITLE
Reloading browser tab on a page with expired session shows Application Error

### ISSUE THREAD

**Issue by gracedigital** [userfrosting/UserFrosting#702]
I left my UF session unattended for a few hours in a tab in FF.  When I came back and reloaded the tab I was shown this error:

![screen shot 2017-05-04 at 1 20 18 pm](https://cloud.githubusercontent.com/assets/13338159/25723348/804d6898-30cc-11e7-8cc4-cdf453114587.png)

Not sure if this is a configuration issue in my environment or is this expected behavior?
Running v4.0.16-Alpha, FF 53.0, macOS Sierra

**Comment by lcharette** [comment]
This is indeed the expected behavior. The proper error is shown when the `production` mode is enabled _or_ the `displayErrorDetails` config is set manually to false. See https://learn.userfrosting.com/error-handling/overview#debugging-modes

I'll leave this issue open for now as it's been discussed we should exclude `AuthExpiredException` from the `displayErrorDetails` in future version (and I can't find another issue for this).   

(Ref. #644)

**Comment by gracedigital** [comment]
I'm probably wrong but it seems like an expired auth/session should get redirected to the login page.

**Comment by lcharette** [comment]
When `displayErrorDetails` is off, this is what's happening

**Comment by alexweissman** [comment]
This behavior has been improved in v4.1.  Since we now delegate the responsibility of determining how to deal with `displayErrorDetails` to the handlers, our `AuthExpiredExceptionHandler` has been reworked to ignore the value of `displayErrorDetails` and always forward to the login page, no matter what.

Please note that this is a breaking change, so it cannot be implemented in 4.0.
