### ISSUE TITLE
CLI command to create a sprinkle

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#729]
The goal of this command is to create an empty Sprinkle and setup everything automatically.

A `sprinkle-skeleton` repo could be used as a base for a new sprinkle. This repo should contain the basic folder structure.

The workflow of the `create-sprinkle` command would be :
- Clone skeleton repo using `composer create-project` command (requires composer php class)
- Setup the sprinkle composer.json with the name and such
- Add the new sprinkle to  sprinkles.json (This will requires #728)
- `composer update` then `bakery bake`

The command would ask, if not already defined using optional options:
- Sprinkle name
- Sprinkle vendor
- Sprinkle folder name

Different skeleton repo could also be used depending what the dev wants to create.

**Comment by alexweissman** [comment]
We could definitely use this sooner rather than later.  We're seeing a lot of people in chat who are getting hung up issues related to in-adherence to the naming conventions.  This command would ensure that directories and namespaces are being named properly and probably save every newbie hours of headache.

**Comment by lcharette** [comment]
UF5 is now created with a skeleton repo; It doesn't require a bakery command, as it's done via composer.
