### ISSUE TITLE
Roles are not deleted in the correct way, in the user zone.

### ISSUE THREAD

**Issue by rafa31gz** [userfrosting/UserFrosting#739]
When adding roles to a user and want to delete them with the delete button, I noticed that this does not delete the row in the HTML, therefore sends an empty parameter and the server detects it as an SQL error.

`General error: 1366 Incorrect integer value: '' for column 'role_id' at row 1 (SQL: insert into `role_users` (`created_at`, `role_id`, `updated_at`, `user_id`) values (2017-06-15 21:45:42, , 2017-06-15 21:45:42, 3))
`
 [app/sprinkles/admin/src/Controller/UserController.php(1147): Illuminate\Database\Eloquent\Relations\BelongsToMany->sync(Array)
](url)

**Comment by alexweissman** [comment]
It would appear that the row _is_ being deleted, but then a "virgin row" is being added in its place with an empty `value`.  The problem seems to be caused by @Silic0nS0ldier's rebase of the `ufCollection` widget.  Apparently, the `!` was dropped from the if condition in this block:
https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/assets/local/core/js/uf-collection.js#L247-L253

It should read:

```
// If we're not using dropdowns, assert that the table doesn't already have a virgin row.  If not, create a new virgin row.
if (!this.settings.useDropdown) {
    var virginRows = this.settings.rowContainer.find('.uf-collection-row-virgin').length;
    if (!virginRows) {
        this._createVirginRow();
    }
}
```
