### ISSUE TITLE
require_email_verification config doesn't work on version 4.1

### ISSUE THREAD

**Issue by cristianosoy** [userfrosting/UserFrosting#741]
I'm trying to disable the email verification when i create a user and i set **require_email_verification**  attribute to false, but doesn't work on version 4.1.

When i try to create a new user from the dashboard using the option "Create User" i received this error:

"Fatal error attempting mail, contact your server administrator. If you are the admin, please check the UF mail log."

Please Help Me.

**Comment by alexweissman** [comment]
Hi @cristianosoy, could you join us in [chat](https://chat.userfrosting.com) and we'll try to get this sorted out?

**Comment by lcharette** [comment]
I managed to replicate this "bug". The `require_email_verification` is observed when [a user is registering](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Controller/AccountController.php#L839), but not when [manually creating a user](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/admin/src/Controller/UserController.php#L148). This is because the default behavior is to send the user a link to reset his password. The admin is not defining a password when creating a user.  So while `require_email_verification` is set to false, an email will still be sent to the user, but not to confirm their email address, but so setup a password. 

I guess there could be an option for this, to disabled sending an email in a situation where the admin set the password for the users... 


Either way, the error received can be still be fixed by setting you your SMTP server in `app/.env`. More info on that error can be found in `app/logs/userfrosting.log`.

**Comment by alexweissman** [comment]
> I guess there could be an option for this, to disabled sending an email in a situation where the admin set the password for the users...

Could someone open up a new issue - feature request for this?
