### ISSUE TITLE
Any reasons why doesn't bakery create the db?

### ISSUE THREAD

**Issue by abdullahseba** [userfrosting/UserFrosting#767]
Bakery probably should have an option to create a db during setup possibly with a one time root login for the purpose.

**Comment by Silic0nS0ldier** [comment]
To my understanding, the built in database drivers connect directly to the database, as opposed to the system that runs the instances. If its possible though, I reckon its worth considering.

**Comment by alexweissman** [comment]
It doesn't look like Eloquent has any built-in support for creating databases; we'd have to [implement our own raw queries for each type of database](https://laravel.io/forum/09-13-2014-create-new-database-and-tables-on-the-fly).  

Raw queries would also be needed to add the necessary db user permissions, and we'd have to get admin credentials from the installing user so that the database could be created and permissions could be applied.

One way this could work is:

1. Ask if this is an installation on an existing database, or if they'd like to create a new database;
2. If they'd like to create a new one, prompt the installing user for admin credentials;
3. Use the admin credentials to create the new database (using raw queries);
4. Generate a new db user (e.g. `userfrosting`), and a random, secure password, and give that user restricted permissions to the new database;
5. Write the database name and newly created user credentials to `.env`.

Would be a bit of work.

**Comment by lcharette** [comment]
> Would be a bit of work.

...for what benefits? I'm still not convinced why this is an issue. If it where, Laravel would support it. It's not necessary for tests anyway.

**Comment by alexweissman** [comment]
Well, the benefit would be that it reduces the complexity of the install process, which is critical to new user onboarding.

**Comment by abdullahseba** [comment]
As I see bakery should not be using any external libraries before composer is run.
Right now to install user frosting you have to 
1. Setup the database manually 
2. Run composer
3. Run bakery.

All 3 items can be done by bakery in that order if it was written to do so.
All bakery has done as far as the install processes goes is combine the migrator and the assets installation.

Thats my tuppence worth put in :)

**Comment by alexweissman** [comment]
Actually, Bakery can't run Composer because Bakery is autoloaded by Composer.  We'd have to have a precompiled distribution of Bakery in order for that to work.

**Comment by abdullahseba** [comment]
Yep bakery relies on  symfony - cli too
That's the whole problem with it. 
Been cli you can have an install.php or something that runs bakery at the end.

**Comment by lcharette** [comment]
Plus Bakery requires Symfony dependencies to work. But Composer can run bakery commands. 

RE the database... while it could be easier for noobs, it’s still IMO part of the server setup process. Like installing PHP and setting up Apache VHost. This is probably historically related to Shared Hosting where you had to create the db in cpanel (and where you where limited in the number of db you could have...). Also keep in mind if noobs uses Vagrant/Docker, the db will already be created. Even *ammp will create the dbs...

Maybe there’s an existing Composer package to do this? Otherwise, it could make a good “up for grabs” issue since it’s low priority.

**Comment by Silic0nS0ldier** [comment]
Well, Bakery couldn't run Composer, but bakery can! There already is an `autoload.php` existence check, and getting PHP to run a command is trivial enough. The question becomes, SHOULD Bakery run composer if needed.

**Comment by alexweissman** [comment]
Actually, if we had a distribution repository (see https://github.com/userfrosting/UserFrosting/issues/830#issuecomment-353110596), then Bakery wouldn't need to run Composer.

**Comment by Silic0nS0ldier** [comment]
Yes, it would. Bakery takes commands from Sprinkles, which in turn can call on their own dependencies.

**Comment by abdullahseba** [comment]
Adding `"post-install-cmd" : "php bakery bake"` to `scripts` in `composer.json` works fine.
Then you can either have a separate script or a custom bakery command to crate the db.
That way as far as the user is concerned, all he has to run is `composer install` to setup uf.

**Comment by Silic0nS0ldier** [comment]
Not a fan of messing with `composer install`, since the command is so heavily associated with dependency installation alone. Plus it'll interfere if all you want to run is `composer install`.

I do have an alternative though. Composer scripts can call other commands, including `composer install` (see [scripts#calling-composer-commands](https://getcomposer.org/doc/articles/scripts.md#calling-composer-commands)). We could have a special "do everything" command, and retain the ability to run everything manually (which can come in handy when debugging).

**Comment by lcharette** [comment]
FYI, Bakery `bake` was once in the `post-install-cmd`. But it creates another issue. When you run composer, ` bake` is always called whatever you do. There are scenarios when you don't want to be called automatically. 

Previously, the issue was because `.env` and `sprinkles.json` weren't created by bakery, to it was baking nothing. Currently the issue is if you don't want to create the admin user (which is done by bake) when running install... which is exactly what you don't want when running composer in the Travis env.

> Make it easy for newb to understand, but don't make it too easy, as they'll be lazy. Teach them how not to be lazy.
