### ISSUE TITLE
Support "non-interactive mode" for migrations and data seeds

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#778]
In order for #777 to work, we need a way to run migrations "non-interactively" if they are to be used in test classes to set up a temporary database.

The problem right now is that they have a dependency on [Symfony's IO class](http://symfony.com/doc/current/console/style.html) ([API](http://api.symfony.com/3.3/Symfony/Component/Console/Style/SymfonyStyle.html)).  One idea was to implement custom classes that shunt all input/output instead of interacting with the console.

The problem with that approach is that we may want to specify some alternative behavior for migrations in "non-interactive mode".  For example, we might want to use Faker to create a fake user account in `CreateAdminUser` during testing.

I can almost see something where we'd support multiple versions of a migration for different environments - the main production migration of course, but then migrations for automated testing, perhaps one for development environments that seeds some fake data, etc.

**Comment by splitt3r** [comment]
I want to test my sprinkle with Travis CI (https://gist.github.com/splitt3r/6b76e66e21e407b5d3455e3cce9d5bab) and have the same Problem.

**Comment by alexweissman** [comment]
Yeah, this actually is pretty important...

**Comment by lcharette** [comment]
What was the best way to fix this? Non interaction means the user question won't be answered. We could move the user creation out of the migrations altogether and into a separate command ?

**Comment by splitt3r** [comment]
I think parameters would be a good choice. Here is an example http://doc.owncloud.org/server/10.0/admin_manual/configuration/server/occ_command.html#command-line-installation-label of how it could look like. I think a createsuper user command like django has makes things more complicated.

**Comment by lcharette** [comment]
The issue is not the verbose option, which is already available from Symfony Console App.
 
Issue is with the user creation that ask unskippable questions. Keep in mind that if we move the user creation outside the migration, in it's own command, since the `bake` command [combine multiple command](https://learn.userfrosting.com/cli/commands#bake), the install flow would be the same for the normal user.

I just wonder if there's any indication where we **shouldn't** have a `create user` cli command. At that point, it should be a normal generic command that can create any user, since by default, the first user is always the master one ?

**Comment by alexweissman** [comment]
So the particular problem I was trying to address, was the ability to automatically set up the testing environment with a dummy "root" user.  It's not that I didn't want to set up a root user, it's just that I didn't want to have to manually provide values just for running automated tests.

I actually like the idea of a `create user` command for other reasons, but it won't solve this particular problem.

What we need here is some way to define different versions of a migration for different environments.  This is also useful for other purposes.  For example, in development I might want to seed some fake data, but in production I might want to import some real data from another source (legacy DB, etc).

**Comment by lcharette** [comment]
I think tests should create their own users (or provide any data) using factories (rather than migrations). So by moving the master user creation to a different command, it will solve part of your issue. The rest can be done in your test setup?

**Comment by alexweissman** [comment]
> I think tests should create their own users (or provide any data) using factories (rather than migrations)

Easier said than done, though.  Some systems might have a very complex web of dependencies on a particular database state.  Reconstructing those in the testing system is not very DRY.  Plus, what if you want to write tests for the migrations themselves?

I can anticipate other situations besides testing where this would also come in handy.

**Comment by lcharette** [comment]
In commit 9bad043, I factored out the admin user creation out of the migration and into it's own `create-admin` command. The `bake` command will automatically call that new `create-admin` command once the migrations have been run, so it shouldn't create any Breaking Change in how the users install UF. Only thing is if a custom migration depends on the now deleted `CreateAdminUser` migration.

You should be able to run migration now using the base command (not `bake`, as it will ask for root user): `php bakery migrate -n`. 

As for creating any user with CLI, I'll open new issues.

**Comment by lcharette** [comment]
I'm not sure how to solve this issue. Current state of `feature-migrator` branch, related to #795, adds the ability for tests to : 
- use transaction;
- use the TestDatabase Trait to use a temp in memory database;
- use the `RefreshDatabase` trait to use a clean, migrated database
- run custom migration using the `migrator` service;
- use Faker to generate data;

Only other thing is to add [Seed data](https://laravel.com/docs/5.5/seeding). Is this necessary, or do we have enough option already? Any other thing that could help this?

**Comment by alexweissman** [comment]
Decoupling table creation from table seeding could help with this issue.  If we have the ability to specify different "migration environments", then one environment could create fake test data, while another environment could seed the tables with real data.

Similarly, one migration environment could do a fresh install, while another environment could perform an upgrade on an existing live database.

The more I think about this, the more it sounds like we need a "playbook" approach - provide a set of tools that let developers define the migration process for different environments, rather than trying to fully define the entire process for them.

**Comment by lcharette** [comment]
(I looked at seeding 4 days ago thinking it woudn't be useful for me, but yesterday I realized it would help a lot with my test/dev env...)

Laravel handles seeding manually (`php artisan db:seed --class=MY_SEED` )  vs migrations that are handled automatically, ie all migrations are run every time migrate is called. I think simply running seeds manually could solve this issue regardless of the env defined in `app/.env` and type of seeds (one time seed or a 'create n user' seed) used. If tests can call the `seeder` service, that's another granular approach  their usage.  And Laravel also have a  `default` seed that is always run. With that, it would be perfect.

a) Migrate db to create tables
b) Run default seeds
c) Cherry pick additional seeds you need for this env.

A particular seed could also be used to  perform an upgrade on an existing live database or even recreate the default permissions if they don't exist anymore.

**Comment by lcharette** [comment]
Should a Sprinkle be able to overwrite another sprinkle seed? Or should we simply have to explecitly have to specify the sprinkle in Bakery command (eg `php bakery seed mySprinkle:mySeed `)

**Comment by alexweissman** [comment]
This is why I was thinking that developers could define higher-level migration scripts/playbooks, which invoke the desired seeds.  Then, a Sprinkle could override at the script/playbook level, rather than individual seeds or table migrations.

**Comment by lcharette** [comment]
I've implemented a basic `seed` command in 27fc69a. I've since used it in my own (private) project and it works ok. 

I think we don't need to add anything else to that command. Overcomplicated mechanism will only makes this a bigger PIA. This basic command acts in the end as a wrapper to write any basic Bakery command since you're not limited to database seeding. Could pose a small security risk, since you can run any code in that class, but so is migrations and everything else. 

Syntax is `php bakery seed [options] <class> (<class>)...` where `class` is the Seed class (or a list of classes) located in each sprinkle `src/Database/Seeder/`. 

I've also included a [ClassFinder](https://github.com/userfrosting/UserFrosting/blob/27fc69ac6be8b3435764f088802ecf50c207d2d5/app/sprinkles/core/src/Util/ClassFinder.php) to locate the seed class across sprinkles. Thing is,  specifying in the command which sprinkle to use will be ugly and impractical. Classfinder acts just like the ressource locator : Find the instance of the class across sprinkle, higher priority sprinkles overwriting lower priority sprinkle. 

With this, I think we can revolve any situation regarding db seeding, except interactive one since the CLI `io` is not passed to the class (so seeds can be executed outside Bakery).

**Comment by lcharette** [comment]
Note to self : only thing left to do to close this issue is document the seeder in learn.

**Comment by lcharette** [comment]
Done in develop !
