### ISSUE TITLE
Uncomment foreign keys in core migrations

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#833]
See https://forums.userfrosting.com/t/foreign-keys-commented-out-in-migration/139

I had commented these out in 4.0, before we had support for migration dependencies.  Now that migration dependencies are supported, we should re-add these.

**Comment by lcharette** [comment]
Note that we should introduce a new migration instead of editing the existing one. Otherwise, existing install will be different than new one. Could also fail when enabling on existing database if existing data doesn't respect the foreign key relations. 

This needs to be handled and tested carefully. I suggest it's taken care of in 4.2 instead,

**Comment by lcharette** [comment]
Fixed in 079142f for UF 4.2 !

A new migration is included in 4.2.0 to add the new constraint with the necessary down migration.
