### ISSUE TITLE
Wrong message when admin resets password for a user

### ISSUE THREAD

**Issue by malle-pietje** [userfrosting/UserFrosting#852]
When an admin resets a password for a user (who has not yet confirmed registration, open registration is disabled) using the "_Send the user a link that will allow them to choose their own password_" option, the message the admin sees is:
**If the email <the email address of user> matches an account in our system, a password reset link will be sent to <the email address of user>.**

No email message is sent to the user's email address which is correct behavior IMHO.

However, I think the message should inform the admin this only applies to users who have set their password or for activated accounts.

**Comment by amosfolz** [comment]
Should be a simple fix. The message [at this line](https://github.com/amosfolz/UserFrosting/blob/master/app/sprinkles/admin/src/Controller/UserController.php#L252-L254) needs to be updated, probably with two new translation sub keys. 

> However, I think the message should inform the admin this only applies to users who have set their password or for activated accounts.

Since this is an access-controlled resource I think it would be safe to even perform a check and then return a different message depending on the outcome. 


I will come back to this once https://github.com/userfrosting/UserFrosting/pull/1006 is merged.

**Comment by lcharette** [comment]
Messages have been updated : 

Old :
<img width="1199" alt="Capture d’écran, le 2023-12-10 à 21 08 14" src="https://github.com/userfrosting/UserFrosting/assets/2566513/965fdcd2-3bf9-4b8f-8566-6a086e4772f5">

New: 
<img width="1201" alt="Capture d’écran, le 2023-12-10 à 21 24 42" src="https://github.com/userfrosting/UserFrosting/assets/2566513/db92d242-d917-4675-b703-a03e14242a8f">
