### ISSUE TITLE
Use custom `PDOStorage` for Rememberme

### ISSUE THREAD

**Issue by lcharette** [userfrosting/UserFrosting#915]
birke/rememberme is not compatible with SQLite. Easier way to fix this would be to use our own `PDOStorage` extension, based on eloquent.

See : 
 - https://github.com/userfrosting/UserFrosting/blob/9755acb8c4c7156ef85dc3c1c4d9e6dc8a6ab3a4/app/sprinkles/account/tests/Integration/AuthenticatorTest.php#L132-L144
 - https://github.com/userfrosting/UserFrosting/blob/9755acb8c4c7156ef85dc3c1c4d9e6dc8a6ab3a4/app/sprinkles/account/tests/Integration/AuthenticatorTest.php#L69-L70

**Comment by Silic0nS0ldier** [comment]
Best to use the `StorageInterface` interface outright. No real advantage in extending `PDOStorage` since everything will be overridden, and get/set connection functions won't be needed.

Aside from the new class, this is all should need to be changed.

https://github.com/userfrosting/UserFrosting/blob/develop/app/sprinkles/account/src/Authenticate/Authenticator.php#L97-L103

**Comment by lcharette** [comment]
[`AbstractDBStorage` ](https://github.com/gbirke/rememberme/blob/d988018169de45a8cfc69ae746e04295d327039c/src/Storage/AbstractDBStorage.php) might have some stuff we need actually, like the set/get columns things.

**Comment by Silic0nS0ldier** [comment]
It depends. If the query builder alone is used, they will be needed. Alternatively using a model removes the need entirely.

**Comment by lcharette** [comment]
Oh right. I got confused with the part in authenticator where you can use the `user_name` or `email` column to log in :P
