### ISSUE TITLE
UF 4.2.1 DefaultPermissions seed results in SQL errors

### ISSUE THREAD

**Issue by noellekimiko** [userfrosting/UserFrosting#981]
UserFrosting Forum thread: https://forums.userfrosting.com/t/defaultpermissions-seed-doesnt-run/543

The Permission class doesn't have an ```id``` property, so the database calls in the syncPermissionsRole() function actually result in SQL errors because the ```permission_id``` is not defined.

I was able to run it by adding this code to the top of the syncPermissionsRole() function:
```
$permissionIds = [];
        foreach ($permissions as $slug => $permission) {
            $permissionIds[$slug] = Permission::where(['slug' => $permission->slug, 'conditions' => $permission->conditions])->first()->id;
        }
```
and then changing the various ```$permissions['PERMISSION_NAME']->id``` calls to be  ```$permissionIds['PERMISSION_NAME']```.

**Comment by lcharette** [comment]
This solution is not perfect as it requires an additional db query. The id is actually generated when [`save`](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Seeds/DefaultPermissions.php#L199) is executed. 

The real problem is `$permissions` [here](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Seeds/DefaultPermissions.php#L32) is not changed by the actions in `savePermissions`. A more simple fix would probably be to pass the variable by reference [here](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Seeds/DefaultPermissions.php#L189):

```
protected function savePermissions(array &$permissions)
```

**Comment by amosfolz** [comment]
This looks like something within my skill set. I will work on it this weekend if no one else gets to it before then.

**Comment by amosfolz** [comment]
> 
> 
> This solution is not perfect as it requires an additional db query. The id is actually generated when [`save`](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Seeds/DefaultPermissions.php#L199) is executed.
> 
> The real problem is `$permissions` [here](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Seeds/DefaultPermissions.php#L32) is not changed by the actions in `savePermissions`. A more simple fix would probably be to pass the variable by reference [here](https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/account/src/Database/Seeds/DefaultPermissions.php#L189):
> 
> ```
> protected function savePermissions(array &$permissions)
> ```

I am trying to follow your logic on this but missing something... Even inside `savePermissions` the ID appears to be missing. I logged `$permissions` that is passed into `savePermissions` and below is a short excerpt: 

```
[create_group] => UserFrosting\Sprinkle\Account\Database\Models\Permission Object
        (
            [table:protected] => permissions
            [fillable:protected] => Array
                (
                    [0] => slug
                    [1] => name
                    [2] => conditions
                    [3] => description
                )

            [timestamps] => 1
            [connection:protected] => 
            [primaryKey:protected] => id
            [keyType:protected] => int
            [incrementing] => 1
            [with:protected] => Array
                (
                )

            [withCount:protected] => Array
                (
                )

            [perPage:protected] => 15
            [exists] => 
            [wasRecentlyCreated] => 
            [attributes:protected] => Array
                (
                    [slug] => create_group
                    [name] => Create group
                    [conditions] => always()
                    [description] => Create a new group.
                )
```
I do not understand how we can do this without another query to DB. Since `id` is generated by DB we need some way to get it...
